### ISSUE TITLE
look likes skim is not buildable at the moment

### ISSUE THREAD

**Issue by hoangtranwork** [lotabout/skim#10]
I tried with nightly rust and there's alot of compile error, recorded here https://asciinema.org/a/5i8k8fzisxhpv1d4yyt73yi0y

**Comment by lotabout** [comment]
@hoangtranwork I noticed that you abort the compilation with `Ctrl-C`. Please be patient and wait for the compilation to end. The shown messages are warnings not errors which should not affect the compilation.

Note that the compilation process is a bit slow. Sorry for that.
