### ISSUE TITLE
[Q] speed issue

### ISSUE THREAD

**Issue by tuyenpm9** [lotabout/skim#107]
Thanks for this port.

I try to test against skim and fzf, probably fzf has better speed compare to skim with same config and pattern.

**Comment by tuyenpm9** [comment]
@lotabout: I don't have proper test, this is from visual test with pure `sk` and `fzf` against same pattern. From same FZF_DEFALT_CMD with `fd` excludes pattern in `.gitignore`, I test against `fzf` and `sk` at the same folder to list files, I can visually see delay to display output with `sk` but smoother and faster with `fzf` when displaying the output. A little flick when `sk` displaying output.

**Comment by lotabout** [comment]
Thanks for report. Sorry that I'll close this issue for now.
Skim is not trying to compete with fzf, it is trying to solve real problems. Thus unless there is a real case showing performance becomes an issue, I'll not try to optimize.
