### ISSUE TITLE
Shell keybinds from fzf

### ISSUE THREAD

**Issue by ar1a** [lotabout/skim#111]
With fzf [i can hit ctrl+r to look through history, ctrl+t to select files, etc](https://github.com/junegunn/fzf#key-bindings-for-command-line). How can I achieve this with skim?

relevant file: https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh

**Comment by lotabout** [comment]
Skim had ported fzf's key bindings: https://github.com/lotabout/skim/tree/master/shell, just do what you would do with fzf.

Say you clone skim's repository to `~/.skim`, then source `key-bindings.zsh` in your `zshrc`:

```sh
source "$HOME/.skim/shell/key-bindings.zsh"
```

**Comment by ar1a** [comment]
thanks! might be useful to add that to the readme :)

**Comment by InnovativeInventor** [comment]
For those who are using fish, I added [this file](https://raw.githubusercontent.com/lotabout/skim/master/shell/key-bindings.fish) as `~/.config/fish/functions/skim_key_bindings.fish` and added 
```
skim_key_bindings
```
to my `config.fish`. Hope this helps!
