### ISSUE TITLE
(Neo)Vim: :SK doesn't display warning for already opened files

### ISSUE THREAD

**Issue by runiq** [lotabout/skim#113]
To reproduce:

```sh
$ touch testfile
$ nvim testfile
# Press ^z to suspend
$ nvim +:SK
# Try to open "testfile"
```

After this, (Neo)Vim freezes. However, the warning window still seems to be there in the background, since I am able to e.g. press `r` to open the file in read-only mode.

**Comment by lotabout** [comment]
@runiq What do you mean by "freezes"?

I tested what you said, and the second nvim shows warning because the swap file exits. I think it is the expected behavior.

**Comment by lotabout** [comment]
Close this due to inactive activity, reopen if you have more information.

**Comment by runiq** [comment]
Sorry, I forgot to report back. I was seeing different behavior on my end (i.e. the warning about the swap file was never shown, but the process reacted to keyboard input *as if* it was shown), so I guess it's something to do with my configuration. This issue can remain closed.

Thanks for following up!
