### ISSUE TITLE
i encounter a error in interative mode .

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [lotabout/skim#117]
hi, i like skim 's interactive mode, but i encounter a error output:
>thread '<unnamed>' panicked at 'byte index 164 is not a char boundary; it is inside 'm' (bytes 163..164) of `weixin-java-mp-demo/README.md:3: ....

and then i press some code it still works. by the way, how to make it faster?  i think it's little slower than fzf.vim in vim

**Comment by FinallyFinancialFreedom** [comment]
`sk --ansi -i -c 'rg --color=always --line-number "{}"'` will cause the problem but `sk --ansi -i -c 'rg --line-number "{}"'` works fine

**Comment by FinallyFinancialFreedom** [comment]
change `"{}"` to `'{}'` will solve this problem for me

**Comment by lotabout** [comment]
Sorry for really slow response. This error is probably related to https://github.com/lotabout/skim/issues/119. 

> `sk --ansi -i -c 'rg --color=always --line-number "{}"'` will cause the problem but `sk --ansi -i -c 'rg --line-number "{}"'` works fine
Both works for me for both `zsh` and `bash`, so I suspect it is related to the input. (maybe it contains non utf8 characters?)

**Comment by lotabout** [comment]
Close. Please reopen if there are updates.
