### ISSUE TITLE
Test failures with 0.5.3

### ISSUE THREAD

**Issue by 5paceToast** [lotabout/skim#128]
I package skim on Alpine Linux (not in edge yet, too busy to get it through the pipeline).
Trying to bump 0.5.2 to 0.5.3 I get two test failures:

```
---- field::test::test_parse_field_range stdout ----
thread 'field::test::test_parse_field_range' panicked at 'assertion failed: `(left == right)`
  left: `Some((0, 0))`,
 right: `None`', src/field.rs:226:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- field::test::test_get_string_by_field stdout ----
thread 'field::test::test_get_string_by_field' panicked at 'assertion failed: `(left == right)`
  left: `Some("")`,
 right: `None`', src/field.rs:360:9


failures:
    field::test::test_get_string_by_field
    field::test::test_parse_field_range
```

Build Environment: see [APKBUILD](https://github.com/5paceToast/user-aports/blob/master/toast/skim/APKBUILD) (this is still the old 0.5.2 one, I test my builds before committing)

I managed to reproduce this on Arch Linux amd64, so it isn't a musl issue.

EDIT: P.S. if/when this is fixed, it would help to have another release, so packagers don't have to disable tests for one release / incorporate temporary patches

**Comment by lotabout** [comment]
@5paceToast Sure! Thanks for report and I'll fix it ASAP.

**Comment by lotabout** [comment]
@5paceToast Done. please use v0.5.4.

**Comment by 5paceToast** [comment]
Can confirm - tests now pass. Thanks :+1:!
