### ISSUE TITLE
--with-nth behavior changed between 0.5.2 and 0.5.4?

### ISSUE THREAD

**Issue by ln-nl** [lotabout/skim#131]
### Steps to reproduce

```
fd .desktop /run/current-system/sw/share/applications/ | sk --delimiter=/ --with-nth=7
```
Version 0.5.2:
![image](https://user-images.githubusercontent.com/44435420/53182479-40697b80-3602-11e9-8a8f-2ea2e15b16a8.png)

Version 0.5.4:
![image](https://user-images.githubusercontent.com/44435420/53182351-fe403a00-3601-11e9-8729-b39d963e589f.png)

**Comment by lotabout** [comment]
Thanks for report! I'll file another release soon since it is critical.

**Comment by ln-nl** [comment]
Thank you!
