### ISSUE TITLE
What is interactive mode?

### ISSUE THREAD

**Issue by alexreg** [lotabout/skim#135]
There's not really an explanation of what it is and how to use it. `-i` is always combined with `-c` in the README examples, but what do these options do *individually*? It would be most appreciated it you could amend the README by beginning the section about "interactive mode" with a description of what is actually is, and what it does.

**Comment by lotabout** [comment]
@alexreg Checkout the following diagram

![skim-interactive-mode](https://user-images.githubusercontent.com/1527040/53381293-461ce380-39ab-11e9-8e86-7c3bbfd557bc.png)

1. Skim could accept two kinds of source: command output or piped input
2. Skim have two kinds of prompt: `query prompt` to specify the query pattern, `command prompt` to specify the "arguments" of the command
3. `-c` is used to specify the command to execute while defaults to `SKIM_DEFAULT_COMMAND`
4. `-i` is to tell skim open `command prompt` on startup, which will show `c>` by default.

So, if the command to execute doesn't contain the replace string `{}`, command prompt is useless. Thus `-i` comes with `-c` almost always.

**Comment by alexreg** [comment]
@lotabout Thank you, that's very helpful! Nice diagram too. Maybe consider putting something similar to this in the README? Up to you, of course.

**Comment by lotabout** [comment]
Sure! Thanks for the suggestion. Close for now.
