### ISSUE TITLE
0.6.0 release cannot be compiled on stable channels

### ISSUE THREAD

**Issue by 5paceToast** [lotabout/skim#139]
So far, the main error I'm seeing is in fuzzy-finder:
```error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)``` in relation to `/src/util.rs`, typically about this line: `use CharType::*;`.

I'm not sufficiently familiar with cargo's build process here, can this be solved by modifying things on skim's side? (e.g adding an explicit dependency to CharType and getting it passed in via `--extern`?

**Comment by lotabout** [comment]
@5paceToast which rust version did you use?

**Comment by 5paceToast** [comment]
@lotabout rust on alpine is currently at 1.31.1
The maintainer hasn't bumped it up to 1.33.0 quite yet, but that's a very recent release.
It'll take even longer for other platforms (such us ubuntu, debian, fedora, and so on) to get a newer version.

Did this behavior change since 1.31.1?

**Comment by lotabout** [comment]
@5paceToast Fixed. Please checkout 0.6.1.

**Comment by 5paceToast** [comment]
Can confirm, 0.6.1 compiles (and runs!) successfully.
Thanks!
