### ISSUE TITLE
execute {} replace does not support the Fields support ranges?

### ISSUE THREAD

**Issue by agroszer** [lotabout/skim#147]
seems to act weird, can't determine what's the logic

e.g.:
`execute(echo {2}>/tmp/skim.txt)`

**Comment by lotabout** [comment]
@agroszer It should work, make sure your delimiter is set correctly by `-d` (default to awk style).

For example:

```
echo "a b c" | sk --bind="enter:execute(echo {2..}>/tmp/skim.txt)"
```

Press `enter` key and `/tmp/skim.txt` will output `b c`. Similarly:

```
echo "a,b,c" | sk -d, --bind="enter:execute(echo {2..}>/tmp/skim.txt)"
```

Will output `b,c`.

**Comment by agroszer** [comment]
oh! yeah I missed `--delimiter ':'`

thx
