### ISSUE TITLE
how to bind to a key combination like shift-ctrl-l ?

### ISSUE THREAD

**Issue by agroszer** [lotabout/skim#152]
Tried `--bind 'shift-ctrl-l:execute(/opt/sublime_text/sublime_text {..2})` and `--bind 'ctrl-shift-ll:execute(/opt/sublime_text/sublime_text {..2})`, but neither seems to work.

A single modifier works fine.

**Comment by agroszer** [comment]
https://docs.rs/tuikit/0.2.4/tuikit/key/fn.from_keyname.html isn't very helpful either...

**Comment by lotabout** [comment]
@agroszer Unfortunately, `ctrl-shfit` combination is not recognized by terminal at all. It won't work.

Btw, you could type `cat` in terminal and then press keys to see the output.

**Comment by agroszer** [comment]
thx
