### ISSUE TITLE
skim utilizes the CPU even when idle

### ISSUE THREAD

**Issue by agroszer** [lotabout/skim#154]
There is plenty of CPU usage when skim sits idle at the `c>` prompt.

Any chance to get that to zero? Might have plenty of instances open at the same time....

**Comment by lotabout** [comment]
@agroszer Just to make sure, "plenty of CPU usage", how much exactly? Mine on Mac is around "1.5%".

**Comment by agroszer** [comment]
xubuntu 18.04 here, 15%-ish

**Comment by lotabout** [comment]
Tried to reproduce on ubuntu 18.04 (Vagrant with 2 Core and 256M RAM) and CentOS, both are around "1.5 ~ 2%".

![image](https://user-images.githubusercontent.com/1527040/55172378-ee91b380-51b4-11e9-9c62-e2cbc8b0a2a3.png)

**Comment by agroszer** [comment]
What desktop did you use? gnome?
Might be something with xfce or my config of xfce... I'll see that I dig further into this.

**Comment by agroszer** [comment]
cool thx!

on a sidenote, when compiling rust spits out some warnings about some constants not being all UPPERCASE
