### ISSUE TITLE
refresh

### ISSUE THREAD

**Issue by agroszer** [lotabout/skim#155]
Using the Preview Window with the stock `preview.sh`, when resizing the terminal or maximizing the terminal text gets garbled.

Any chance to get a full refresh?

**Comment by lotabout** [comment]
@agroszer What you mean by "garbled"? Could you share an example(maybe a screenshot)?

**Comment by agroszer** [comment]
This is how it looks after maximizing the (xfce4-)terminal with F11.
The right side preview is the 'new' -- that gets updated, the left side preview is the dead one.

![Screenshot_2019-03-27_12-23-57](https://user-images.githubusercontent.com/350912/55072401-4b914a80-508b-11e9-9439-3b4aa15a7c61.png)

**Comment by agroszer** [comment]
This is how it looks when I drag a corner of the terminal to resize

![Screenshot_2019-03-27_12-26-39](https://user-images.githubusercontent.com/350912/55072513-9e6b0200-508b-11e9-9bdc-e7fee53b20b9.png)
