### ISSUE TITLE
preview 'lags' behind

### ISSUE THREAD

**Issue by agroszer** [lotabout/skim#158]
using the latest master, the preview lags 'one move' behind

starts with blank, then on the first `<up-arrow>` the preview shows what should have been shown at start

I'm using `sk --delimiter ':' --ansi -i -c 'rg --color=always --line-number "{}"' 
    --preview "skim_preview {}" 
    --cmd-query TEXT`

**Comment by lotabout** [comment]
@agroszer Confirmed. Thanks for report.
