### ISSUE TITLE
Is there a way for the preview command to know the current query?

### ISSUE THREAD

**Issue by sanga** [lotabout/skim#159]
I have a file preview command that is basically a script wrapper around bat that highlights the lines for a given search term. I'd like use this as the preview command for sk, but I don't think the current query gets passed through to the preview command when `--print-query` is enabled?

**Comment by lotabout** [comment]
@sanga Currently no, I'll try to add it later.

**Comment by lotabout** [comment]
@sanga Placeholder `{q}` for current query is not supported. It has nothing to do with `--print-query`.

**Comment by sanga** [comment]
This doesn't appear to work to me. Tried with this:

`sk --ansi -i -c 'rg --color=always --line-number "{}"' --delimiter=: --preview "echo {q}"`

as compared with this, that works:

`sk --ansi -i -c 'rg --color=always --line-number "{}"' --delimiter=: --preview "echo {1}"`

**Comment by lotabout** [comment]
@sanga Em.. I see. Actually in skim there are two kinds of query: 
- `cmd-query` is used to replace the command specified by `-c`
- `query` is used to filter the choices.

Currently `query` is supported but not `cmd-query`.

**Comment by lotabout** [comment]
@sanga Try out `{cq}` for command query which is the one you use for invoking `rg` in your case.

**Comment by timsampsoncujo** [comment]
looks good to me. Thanks!

**Comment by sanga** [comment]
looks good to me. Thanks!
