### ISSUE TITLE
Add an option to separate output with NULL chars

### ISSUE THREAD

**Issue by krigstask** [lotabout/skim#161]
Adding an option like this (`-0`, for example) would simplify processing _skim_'s output (selection) with tools like `xargs`.

Probably it's worth to consider adding support for NULL-separated input, too.

**Comment by lotabout** [comment]
@krigstask Already  supported by `sk --print0`

**Comment by krigstask** [comment]
Whoops, sorry, I was searching man page for `-0`, `-z` and `NULL`, and missed both `print0` and `read0`.  My bad!
