### ISSUE TITLE
Separate colors for input text + unmatched text

### ISSUE THREAD

**Issue by dgrisham** [lotabout/skim#163]
I'm interested in anyone's thoughts (@lotabout?) on separating the colors for unmatched results and the input text. I was playing with the color settings in `skim`, and thought it'd be nice if I could set the color of text that isn't 'matched' in any way to be a dark gray on black, then have matched text be white. This would provide a nice contrast between unmatched and matched text. However, currently it seems that unmatched text is the same as normal text, which means that input text would also be dark gray to achieve this (and I'd rather set the input text to be brighter).

**Comment by lotabout** [comment]
@dgrisham What do you mean by `unmatched text`?
For example, with input "hello world" and pattern "hw", the result would be `[h]ello [w]orld`. Could you illustrate what is "normal text" and what is "unmatched text"?

**Comment by dgrisham** [comment]
@lotabout Right, that was unclear on my part. In the example of the pattern `hw` and input text `hello world`, I would consider the text in `[]` 'matched' text and that in `()` 'unmatched' text: `[h](ello) [w](orld)`. By 'normal' text, I mean the text in the input prompt.

**Comment by lotabout** [comment]
New color terms added: `query` and `query_bg` for setting the "normal" text you described here.

**Comment by dgrisham** [comment]
Thanks @lotabout!
