### ISSUE TITLE
Transparent/no background color

### ISSUE THREAD

**Issue by dgrisham** [lotabout/skim#164]
I'm hoping to get transparent/no colors set on all of the background colors in `skim`. I'm using urxvt with transparency so that my wallpaper is dimly visible, so whenever a background color is set by a program it's obvious and overrides the wallpaper.

If I don't pass in a value for `bg` to `skim` then I get the transparent background as desired. So, from [what I've seen in theme.rs](https://github.com/lotabout/skim/blob/6d9b673d25a216c06626651be5a8da63f21c2e2c/src/theme.rs#L8), I basically want a way to set `current_bg` and `matched_bg` to the equivalent of `Color::Default` via the CLI args.  I've tried setting these with ANSI codes, which I'm admittedly unfamiliar with, e.g. `sk --ansi --color=current_bg:'\e[49m'`, but that doesn't seem to change anything.

Any ideas here? I know that I could always compile my own version of skim with a custom theme, but I'd rather avoid it if possible. One solution could just be to have a purely empty theme (so, all colors set to `Color::Default`) so that the user can specify only the colors they want to be set, but I'm not sure whether that's necessary.

**Comment by dgrisham** [comment]
Hm, maybe this is what the `bw` ('no colors') option was meant to do? Doesn't seem to be implemented as far as I can tell.

**Comment by lotabout** [comment]
@dgrisham In the latest commit
- `bw` is implemented for `black & white`
- `empty` is implemented for setting all as `Color::Default`.
- Besides, `fg:-1` the `-1` ANSI value is treated as `Color::Default`.
