### ISSUE TITLE
UI is not responsive while reading large input list

### ISSUE THREAD

**Issue by wincent** [lotabout/skim#170]
Thanks for making Skim.

I'm trying it out and the ordering of the results is much improved over fzf. However, I find that the input UI is almost totally unresponsive when processing large inputs, as demonstrated in this gif:

![ScreenFlow7](https://user-images.githubusercontent.com/7074/57510756-d65e9980-7307-11e9-813a-e2d92cb5a267.gif)

On the left:

- Run `fzf` in a directory with many files (about 348k); type query ("frontend js web") and see keystrokes immediately reflected. Total time about 5 seconds.

On the right:

- Run `sk` in the same directory and type the same query; see it take about 25 seconds to actually reflect the keystrokes.

**Comment by lotabout** [comment]
@wincent Thanks! for report, it is a known issue and I'll try to fix in next release.

Now the thread for handling user input and merging the filtered items is the same, so that if the input is too large, the thread will be blocked for user input.

**Comment by wincent** [comment]
>  it is a known issue and I'll try to fix in next release.

@lotabout: That's great news. Thanks for your work on this.

**Comment by lotabout** [comment]
@wincent Would you please try out branch `ticket-170` and check if it improves your situation?

**Comment by wincent** [comment]
@lotabout: I just built your PR and it is a massive improvement. Here's a GIF of the same search as above, in the same big repo:

![ScreenFlow](https://user-images.githubusercontent.com/7074/58549856-c2be9880-820c-11e9-8ae8-42347097ccbf.gif)

**Comment by lotabout** [comment]
@wincent Great! Then I'll close this issue. Thanks again for the report and testing.
