### ISSUE TITLE
sk-tmux does not pass SKIM_DEFAULT_COMMAND

### ISSUE THREAD

**Issue by chmp** [lotabout/skim#172]
I have been playing around with skim and do not seem to be able to customize the default command when using `sk-tmux`. After looking at the source of the `sk-tmux` wrapper, I am wondering whether these lines are correct:

```bash
[[ -n "$SKIM_DEFAULT_OPTIONS" ]] && envs="$envs SKIM_DEFAULT_OPTIONS=$(printf %q "$SK_DEFAULT_OPTIONS")"
[[ -n "$SKIM_DEFAULT_COMMAND" ]] && envs="$envs SKIM_DEFAULT_COMMAND=$(printf %q "$SK_DEFAULT_COMMAND")"
```

Shouldn't the variables after `printf` be also prefixed with `SKIM_` instead of `SK_`? 

I solved my issue for now, by setting both `SKIM_DEFAULT_COMMAND` and `SK_DEFAULT_COMMAND`.

**Comment by lotabout** [comment]
@chmp You're correct. Would you like to submit a PR for this :)

**Comment by chmp** [comment]
Sure. Will do. Give me a sec.

**Comment by chmp** [comment]
I created a PR [here](https://github.com/lotabout/skim/pull/173).

**Comment by lotabout** [comment]
Thanks! merged, closing.
