### ISSUE TITLE
sk is unrepsonsive when using `--preview=head`

### ISSUE THREAD

**Issue by sanga** [lotabout/skim#176]
Seems like it ignores searching filtering input. Steps to repro:

- `cd / && sk --preview=head` (though I think the actual preview cmd is irrelevant)
- start typing to filter the list
=> no input/filtering

Might be related to #175, at least I haven't noticed this before

**Comment by lotabout** [comment]
@sanga Em... It shouldn't be working at all.

> cd / && sk --preview=head (though I think the actual preview cmd is irrelevant)

Actually it IS relevant. Commands waiting for input like `head` will eat up the inputs that was supposed to to to skim, thus making skim unresponsive.

Maybe what you want is `cd / && sk --preview="head {}"`?

**Comment by balta2ar** [comment]
@lotabout Could you please cut new release after you sort this issue out? Improvements regarding the input responsiveness are affecting me as well. Thank you!

**Comment by lotabout** [comment]
@balta2ar Did you meet similar issues?
I think this issue is caused by invalid use of skim and wouldn't happen in normal cases. Say:
- `preview=head` would waiting for(and eat up) user input, but normally it's meaningless in preview.
- `preview="head {}"` is normal since it will take the filename and print the head lines. This command has no problem.

**Comment by balta2ar** [comment]
Sorry, I meant to say that I'm looking forward to seeing a release with this fix: #175. I have no troubles regarding the current issue, I should've probably comment in the other issue report.

**Comment by lotabout** [comment]
@balta2ar I see, sorry that I misunderstood. I'll file another release soon.

**Comment by sanga** [comment]
Sorry for the noise - not quite sure what I was thinking (note to self: don't file bugs with the flu)
