### ISSUE TITLE
[switching from fzf] vim plugin questions

### ISSUE THREAD

**Issue by ahmedelgabri** [lotabout/skim#182]
I'm currently thinking about switching from `fzf` to `skim`, my current usage is both in vim & on the CLI. The CLI usage is simple enough to be replaced but my issue is I'm using `fzf.vim` & used to commands like `:Buffers`, `:Colors`, etc…

- How can I implement these with the current vim plugin?
- Any plans to move the plugin to a separate repo? I install `sk` through homebrew & doesn't make sense to clone the full repo inside `.vim` too to get the plugin

**Comment by lotabout** [comment]
There is a clone of fzf.vim: [skim.vim](https://github.com/lotabout/skim.vim). So just like what you did with fzf, add the following lines into your vimrc(example with vim-plug):

```
Plug 'lotabout/skim', { 'dir': '~/.skim', 'do': './install' }
Plug 'lotabout/skim.vim'
```

And use `PlugInstall` to install to get it working.

**Comment by ahmedelgabri** [comment]
I guess I was confused a bit with https://github.com/lotabout/skim.vim README since it has `fzf` still all over it so I assumed it was still WIP or something. Thanks, will check it out then 👍
