### ISSUE TITLE
Validate selection on hitting enter

### ISSUE THREAD

**Issue by bbqsrc** [lotabout/skim#191]
I'm using skim as a library with quite a lot of success, however, there is one caveat: I am using it with a list of items that a user must select at least one, and if the user types a query that results in 0 results and hits enter, it returns `None`.

Is there a way to augment this behaviour?

**Comment by lotabout** [comment]
@bbqsrc Sorry for really late response. I believe the latest skim would no longer return `None`. Could you please help confirm that? Thanks!

**Comment by bbqsrc** [comment]
I'll have a look and let you know. When you say it doesn't return None, do you mean that the user cannot accept zero options or that it returns something else now?

**Comment by lotabout** [comment]
@bbqsrc On accept 0 or more items, skim will return 

```rust
pub struct SkimOutput {
    pub accept_key: Option<String>,
    pub query: String,
    pub cmd: String,
    pub selected_items: Vec<Arc<dyn SkimItem>>,
}
```

So that you could distinguish `accept` and `abort` events and maybe throw error message to the user accordingly. Currently there is no way(hook) to reject zero options in skim's side. Hope that meet your needs.

**Comment by lotabout** [comment]
Close for now, please reopen if you have further questions.
