### ISSUE TITLE
Case insensitive matching and smart-case

### ISSUE THREAD

**Issue by egrieco** [lotabout/skim#195]
# Feature Request

**Case insensitive matching and smart-case**

A big part of the reason that I use programs like Skim and fzf is the ability to "try" queries without having to waste too much time thinking about exactly what I need to type. Thus case-insensitive queries are frequently a lot more useful than case-sensitive queries.

The most convenient mode would be a **smart-case** query where all-lower-case queries are treated as case-insensitive while queries containing upper case letters are treated as case-sensitive.

**Comment by lotabout** [comment]
@egrieco The fuzzy search algorithm *is* case-insensitive. It’ll try it’s best to match your query.
