### ISSUE TITLE
[Feature Request] access command prompt from preview

### ISSUE THREAD

**Issue by avshyz** [lotabout/skim#203]
Right now, writing `{}` on the value of `-c` would replace it with the command prompt, 
but writing `{}` on the value of `--preview` would replace it with the selected line.
I think adding a way to access the prompt from the preview would be awesome.

Right now, I'm trying to implement an interactive git pickaxe search with this line
`sk -ic "git log -S{} --oneline" --preview="echo {} | cut -f1 -d' ' | xargs git show"`
Typing would find commits which's diff contained the string typed, while the preview showed the content of the commit.
It works perfectly. Almost.
If I were able to replace the last part with `xargs git show -S{q}`, which would replace `{q}` with the typed value, the preview would be a lot more usable (as it'd only show the hunk containing the string I was looking for).

What do you think? :)

**Comment by lotabout** [comment]
@avshyz Which version do you use? It should already be supported since v0.6.7.

**Comment by avshyz** [comment]
Hi @lotabout!
I'm using 0.6.8

**Comment by avshyz** [comment]
Ok, I've managed to find it once I looked into the release notes. Maybe it's worth adding it to the readme? :)
