### ISSUE TITLE
Using SKIM as a library immediately crashes unless tabstop is set

### ISSUE THREAD

**Issue by SirVer** [lotabout/skim#205]
The crash looks like this:

```
> thread '<unnamed>' panicked at 'attempt to calculate the remainder with a divisor of zero', /cargo/registry/src/github.com-1ecc6299db9ec823/skim-0.6.8/src/util.rs:174:23
```

The line takes the modulo of `tabstop`, which is [set to zero](https://github.com/lotabout/skim/blob/master/src/selection.rs#L65) by default (I believe this should just be 8 and this bug is gone). It only changes its value, when `Options::tabstop` is set [here](https://github.com/lotabout/skim/blob/master/src/selection.rs#L92), interestingly the default of 8 is used here should parsing fail.

Hence, the workaround for library users currently is:

~~~
let options = SkimOptionsBuilder::default()
   .tabstop(Some("8"))
~~~

**Comment by pierrechevalier83** [comment]
Hey, @lotabout, would you mind releasing a new minor version of skim to crates.io so consumers of this library don't have to workaround this bug in their codebase, as I had to here: https://github.com/pierrechevalier83/find_unicode/blob/bd18b4bf6d0a2d187abcb4c1cf478a192b198f5e/src/main.rs#L64?

**Comment by lotabout** [comment]
@pierrechevalier83 Sure, just done.
