### ISSUE TITLE
Multi selection including unselected option

### ISSUE THREAD

**Issue by tpoliaw** [lotabout/skim#210]
$ sk --version
    0.6.8

This might be intended behaviour but it caught me out by being different to fzf.
When using skim with the `--multi` flag, the line the cursor is on when you hit enter is included in the returned selection, even if it hasn't been selected. There are often times when I search/scroll through a list and find there are no more options that need selecting but would have to scroll back to the previous selection to prevent an unwanted option being included.

Is there an option to change this behaviour so that only explicitly selected items are selected?

**Comment by lotabout** [comment]
After the fix, skim behave like this:

1. If multi-selection is not enabled, select current item
2. If multi-selection is enabled
    a) No item is selected -> select current item
    b) already selected some items -> exclude current item

It should be compatible with fzf.
