### ISSUE TITLE
Strange characters on first line (fish)

### ISSUE THREAD

**Issue by muellerj** [lotabout/skim#211]
After switching from `zsh` to `fish`, I get some strange characters on the first line after invoking `sk`:

![Screenshot 2019-08-11 at 20 07 44](https://user-images.githubusercontent.com/53246/62837826-5cc2a880-bc74-11e9-9b8f-2bf024f3595c.png)

Setting/unsetting `SKIM_DEFAULT_{COMMAND,OPTS}` does not change the behaviour, neither does changing the prompt (my initial suspicion).

Under `zsh`, the problem vanishes:

![Screenshot 2019-08-11 at 20 14 17](https://user-images.githubusercontent.com/53246/62837855-aa3f1580-bc74-11e9-8456-fc72bd887db9.png)

**Comment by lotabout** [comment]
@muellerj Could you please share the environment variables.

```
env | grep SK
```

**Comment by muellerj** [comment]
Sure:

![image](https://user-images.githubusercontent.com/53246/62851047-23765100-bce5-11e9-860e-26c243a57214.png)

**Comment by lotabout** [comment]
@muellerj Em... Very strange. I cannot reproduce under both Linux and MacOS. Could you please help to:

1. Try `fd -H --exclude .git | sk`
2. Try `find . | sk` to see if it is related to `fd`'s output.
3. Try skim in another directory to double check if it could be the problem of some files?
4. Finally it is possible to start an empty fish shell(no customization) and check if it still happens.

Thanks!

**Comment by muellerj** [comment]
@lotabout: Thanks for your help.

1. `fd -H --exclude .git | sk` shows no strange characters.
2. `find . | sk` is also free of strange characters
3. Running `sk` under `/tmp/foo` (freshly created) shows the strange characters
4. Running `sk` in a fresh fish shell (I simply renamed `~/.config/fish`) shows no strange characters

It seems the bug is somehow connected to my prompt? Any idea where I could start to search?

**Comment by muellerj** [comment]
Update: I think I may have found the culprit: I'm sourcing the base16 colorschemes from chriskempson/base16-shell in order to set the colors of my shell. These output a bunch of escape codes:

```
$ bash -c "source ~/.config/base16/wombat.sh" > colorcodes.txt
$ bat colorcodes.txt
───────┬────────────────────────────────
       │ File: colorcodes.txt
───────┼────────────────────────────────
   1   │ 4;0;rgb:11/11/11^G4;1;rgb:
       │ ff/61/5a^G4;2;rgb:dd/f8/8f^G[0m
       │ \4;3;rgb:fa/d0/7a^G4;4;rgb
       │ :dd/aa/ff^G4;5;rgb:a5/c7/ff^G
       │ 4;6;rgb:b7/ff/f9^G4;7;rg
       │ b:ee/ee/ee^G4;8;rgb:ee/e5/b2
       │ ^G4;9;rgb:ff/61/5a^G4;10;
       │ rgb:dd/f8/8f^G4;11;rgb:fa/d0
       │ /7a^G4;12;rgb:dd/aa/ff^G4
       │ ;13;rgb:a5/c7/ff^G4;14;rgb:b
       │ 7/ff/f9^G4;15;rgb:de/da/cf^G[0m
       │ \4;16;rgb:f5/8c/80^G4;17;r
       │ gb:ff/ff/ff^G4;18;rgb:31/31/
       │ 31^G4;19;rgb:b1/e9/69^G4;
       │ 20;rgb:5d/a9/f6^G4;21;rgb:eb
       │ /d9/9c^GPgeeeeee^GPh11111
       │ 1^GPieeeeee^GPjb1e969^G[0m
       │ ]Pkeeeeee^GPleeeeee^GPm11
       │ 1111^G
───────┴────────────────────────────────
```

I suspect that these escape sequences somehow end up in sk, when it spawns a new process to run its `SKIM_DEFAULT_COMMAND`?

**Comment by muellerj** [comment]
I can lock these away under a conditional, such that non-interactive shells never see the escape-sequences

``` fish
if status --is-interactive
  bash -c "source ~/.config/base16/wombat.sh"
end
```

Please consider my immediate problem solved, unless you want to rework the way these are handled by Skim.
