### ISSUE TITLE
Matching not fuzzy using -c 'rg {}'

### ISSUE THREAD

**Issue by heliostatic** [lotabout/skim#212]
When using `-c 'rg {}'`, matching does not appear to be fuzzy anymore.

![2019-08-19 14 28 58](https://user-images.githubusercontent.com/70898/63289719-c69f0b80-c28d-11e9-8697-19004ad2dfda.gif)

**Comment by lotabout** [comment]
@heliostatic This is by design. The command provided by `-c` option serve as the source of the items, skim has no way to control their behavior.
If you need to narrow down the items returned by `rg`, you could still press `C-q` to switch to the fuzzy mode.

**Comment by heliostatic** [comment]
Ah, I misunderstood what `-i` was doing in this case. Removing it gave the behavior I expected. Thanks!
