### ISSUE TITLE
Hook methods for string display would be useful

### ISSUE THREAD

**Issue by alok** [lotabout/skim#216]
Builds off #80.

One issue in that thread:

> I have no control over how items are previewed - I want to turn items into a text preview myself, not rely on external commands.

with the proposed solution:

> methods like `do_display() -> String` or `upon_selection()` or `preview_text() -> String` that allows me hooks into what skim does with items.

In my case, I want to display a shortened filename and the contents of that file at a specific line, and when a user selects that, jump to the correct file.

Right now, I have a hashmap from filenames to lines in those files (`HashMap<PathBuf, Vec<String>>`), and getting the original filename from the shortened one is difficult. I'd prefer to just have display lines that correspond to the underlying data but have a different string representation.

**Comment by Rudo2204** [comment]
I'm running into this problem as well.
Right now I'm having the program calling itself and use a helper function to get the preview I want, an ugly solution but it works okay for now.
It would be nice to have this feature.
