### ISSUE TITLE
Implement --select-1

### ISSUE THREAD

**Issue by focusaurus** [lotabout/skim#218]
Any plans to implement `--select-1` functionality? My main `fzf` command is: `fzf --select-1 --exit-0 --query "$1"` so once that works I could switch to skim.

**Comment by unclechu** [comment]
I went to the *issues* to ask about why it is mentioned in the `--help` but doesn't work as expected. So it seems it just isn't implemented yet?

**Comment by unclechu** [comment]
Ah, I should have read usage info more carefully, it's in *not used for now* section.
