### ISSUE TITLE
Exact matching mode without case sensitivity?

### ISSUE THREAD

**Issue by marty-oehme** [lotabout/skim#219]
It seems the fuzzy matching mode is always case insensitive, and the exact matching mode is always case sensitive. 

However, is there any way to get the contiguous matching mode that exact provides (i.e. match whole words) while not having to also match the case? In other words, is it possible to set exact mode to case insensitivity, or smart-case?

For explanation: My use case is full-text searching my notes (with rg) and then searching over the output with skim. Matching the output with the fuzzy matcher mostly shows completely unrelated notes, and exact matching shows the perfect answers *except* for always having to search for the right case.

**Comment by Wonko7** [comment]
Same thing when skimming through book titles, I know the words, not the case.

**Comment by lotabout** [comment]
@marty-oehme The new fuzzy matching algorithm comes with smart case support as well as giving more bonus to consecutive matching. Would you please have a try to see if it suits your requirement?

As for case insensitive "exact mode", I think it may not be suitable to be the default behavior. I'll think more about that later.

**Comment by marty-oehme** [comment]
@lotabout Thanks for the response! Unfortunately, due to this issue I had to switch my fuzzy matcher from skim and am generally a bit strapped for time right now.

As soon as I find the time to take the new algorithm for a sufficiently extensive test-run I will definitely let you know. Thanks again for taking the issue into consideration!

**Comment by Wonko7** [comment]
> giving more bonus to consecutive matching
I tested 0.7.0: the results are fine with a small number of choices (switching vim buffers), but for digging through shell history if I don't use exact mode I never reach old entries. And if I use exact mode it only works if I'm sure of the case. 
Could the adjacency bonus be adjustable? If it's high enough maybe exact mode won't need an insensitive version (I agree it shouldn't be the default behavior).

**Comment by muellerj** [comment]
I would 👍 an `exact` + `case-insensitive` option.

**Comment by lotabout** [comment]
An option was added `--case [respect,ignore,smart]`. Apply `--case ignore` will do case insensitive matching in exact mode.

**Comment by marty-oehme** [comment]
Thank you @lotabout, this is super useful!

**Comment by Wonko7** [comment]
Perfect! Thank you!
