### ISSUE TITLE
bat highlight-line not working properly

### ISSUE THREAD

**Issue by petobens** [lotabout/skim#220]
As it can be seen in the image, if I run `sk --preview 'bat --color always --style numbers --highlight-line 5 {1}'`, the (5th) line is only partially highlighted in the preview window:

![image](https://user-images.githubusercontent.com/2583971/64490842-91a42a00-d237-11e9-99f8-f59336ec5434.png)

It seems to be a problem with skim since bat line highlighting  works just fine:

![image](https://user-images.githubusercontent.com/2583971/64490860-d6c85c00-d237-11e9-950c-2d1dee961255.png)

**Comment by lotabout** [comment]
Should be fixed? Tested on MacOS + current master.
![image](https://user-images.githubusercontent.com/1527040/70593585-91417380-1c18-11ea-8e81-22106a753304.png)
