### ISSUE TITLE
Feature request: tab-completion on steroids (take an option from the list to the enter field)

### ISSUE THREAD

**Issue by chubin** [lotabout/skim#223]
(cc from my email from `Date: Sun, 22 Sep 2019 18:45:15 +0300`)

What do you think about this feature: copy one of the alternatives in the list
to the enter field? Something like tab completion on steroids.

*Details:*

Consider Google Suggest.
Of course, we are talking not about real Google Suggest feature,
I am just using it as an example.

Say, I am searching for
```
    "python regex substitute group lambda function"
```
I enter:
```
    c> python regexp substitute
```
And I get:
```
    python regex substitute all
    python regex substitute group
    python regular expression substitute variable
    python regular expression substitute group
    python re substitute string
    python re substitute all
    python re substitute group
    python regular expression substitute
    python re substitute
    python regex substitute
```

I can scroll through the options,
but I want to pick some and just copy it into the
enter field, and continue with it.

Say I want to pick the 4th one
(`python regular expression substitute group`)
and enter the rest "... lambda function".

It would be great if I could just press "Tab" or "Shift-Enter"
or something like that for it.

**Comment by lotabout** [comment]
@chubin I finally had time to think about the feature. Skim is intended to be a simple fuzzy finder, not a general framework(e.g. Python's [prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit)). Sorry that I won't implement this even though I do think it is a nice feature.
