### ISSUE TITLE
Feature request: two types of lists: completions/answers

### ISSUE THREAD

**Issue by chubin** [lotabout/skim#224]
Feature is related to #223

If it possible to take an alternative from the list, and use it in the input field (tab-completion on steroids), it would be great to have two types of the lists (maybe one is above the input line and one is below it, or maybe some sort of key for switch): with the "completions" and with the "answers".

*Details*

Consider Google suggest again.

We enter "python regexp substitute" again and we have
the list of suggestions:

    python regex substitute all
    python regex substitute group
    ...

But at the same time we have list of the real answers too:

    Python string.replace regular expression
    python .replace() regex
    Python re.sub(): how to substitute all 'u' or 'U's
    Python Regex instantly replace groups
    ...

What would be really cool to have, if we could have something like
two lists, and we could use the first one as the suggestion list
and the second one as the options list.

        Python string.replace regular expression                |
        python .replace() regex                                 |
        Python re.sub(): how to substitute all 'u' or 'U's      |
        Python Regex instantly replace groups                   |
    c>  python regex
        python regex substitute all                             :
        python regex substitute group                           :

For that, two different command line options could be used,

    -i and
    --suggestion-interactive

**Comment by lotabout** [comment]
Will not implement to keep skim simple.
