### ISSUE TITLE
Change name of binary sk -> skim?

### ISSUE THREAD

**Issue by zsugabubus** [lotabout/skim#229]
Sorry, but I just can't stand asking why did you name the binary `sk` instead of `skim`. Here is my reasoning:
* `skim` is just two letters more than `sk`, not one hundred.
* If you want making your configuration permanent, you will create an alias (or similar) for `sk`, so you surely never will call it directly.
* If you don't care about configuration and you say you just want filter through some text quickly, you can also create a single-letter alias that automagically expands to `| skim`.
* (My biggest pain is that) `sk` pollutes user's two-letter abbreviations name space.

**Comment by lotabout** [comment]
@zsugabubus Sorry that I won't fix this. Well... I think the shorter the better...
