### ISSUE TITLE
Search inside text files

### ISSUE THREAD

**Issue by leodasvacas** [lotabout/skim#23]
It would be cool to be able to match text inside text files.

**Comment by lotabout** [comment]
@leodasvacas Could you describe your expectations in more detail?

BTW, skim has an `interaction mode` which allows you to use it as an interface to invoke other commands such as `ag`. I don't know whether #9 is what you want or not.

**Comment by leodasvacas** [comment]
That's what I want and it's well explained in the readme, thanks!
