### ISSUE TITLE
Ctrl-J accepts match in ZSH

### ISSUE THREAD

**Issue by Konfekt** [lotabout/skim#232]
`Ctrl-J`, instead of moving the selection bar down, accepts the match in `ZSH 5.6` under `Linux x64` with Skim 0.60. It used to work fine in 0.55.

**Comment by Konfekt** [comment]
This only happens if `sk` is called by a binding, for example
```sh
f() { ls | sk }
zle -N  f
bindkey  "^S" f
```

**Comment by jfrankenau** [comment]
I have the same issue. It is probably due to `CTRL-J` issuing a LF and therefore it is never bound to the `down` action.

**Comment by Konfekt** [comment]
> It is probably due to CTRL-J issuing a LF 
Yes, the [ascii-table](http://ascii-table.com/control-chars.php) shows Ctrl-J to issue a LF.

> Maybe the problem lies within tuikit.
Since the switch to tuikit came with 0.60, this is likely.

Just as a side note, the same issue happens in Konsole, xterm and Urxvt. Curiously, not in the WSL xterm terminal.
