### ISSUE TITLE
Feature: preview mouse scroll

### ISSUE THREAD

**Issue by MeisterTea** [lotabout/skim#233]
I think it's a dupe of https://github.com/lotabout/skim/issues/183 but since it's closed, I am opening a new one.

Would it be possible to allow the user to scroll down/up with the mouse instead of shift+[down|up] ?

This functionnality is in fzf

**Comment by MeisterTea** [comment]
Hi, I wanted to switch to skim and ditch fzf but it seems that you had to revert the mouse support feature. Do you have any idea if you are going to add it back ?

**Comment by lotabout** [comment]
Previous implementation was incomplete that it only deals with preview window, not the item list window. I'll reopen this issue and try to work out a better solution.
