### ISSUE TITLE
Mouse not released after skim exits and other issues

### ISSUE THREAD

**Issue by lilydjwg** [lotabout/skim#235]
* Run skim and exit, the mouse is still being used but no program is using it (mouse clicks produce escape code sequences)
* Run skim and have items in the list, mouse wheels don't scroll the selected item
* Adding `--no-mouse` argument will help and it's compatible with older versions, but I hate breaking changes. Could you avoid that?

**Comment by lotabout** [comment]
Yeah. The mouse support is not implemented correctly. I'll revert the support for now, and think through it first.
