### ISSUE TITLE
Skim not working properly with ansi input

### ISSUE THREAD

**Issue by johnpyp** [lotabout/skim#245]
Using:
```
fd --color always | sk --ansi
```
Displays most colors, but not for current-directory files seemingly, whereas
```
fd --color always | fzf --ansi
```
Does what I expect. I'm not sure exactly where this issue is, but I'm noticing it now using this as my default file finder over fzf.

**Comment by lotabout** [comment]
@johnpyp which version did you use?

**Comment by johnpyp** [comment]
0.6.9

**Comment by lotabout** [comment]
Confirmed problem still exists on master.

**Comment by lotabout** [comment]
I've done some more tests and realized that it should be fixed in #231.

@johnpyp Could you please test if the problem still exist on master branch? Thanks!

**Comment by johnpyp** [comment]
Yeah, seems to work on master. Thanks :)

**Comment by lotabout** [comment]
Thanks! close.
