### ISSUE TITLE
Will this greate project support windows?

### ISSUE THREAD

**Issue by hh9527** [lotabout/skim#25]
At least, can avoid features which block in windows?

**Comment by lotabout** [comment]
Thanks!

But sorry that windows will not be supported. The main reason is `skim` depends on `ncurses` to show the search result(UI) which does not support windows...

**Comment by hh9527** [comment]
Maybe https://github.com/ihalila/pancurses will help to support windows.

There is a TUI project (https://github.com/gyscos/Cursive) rely on this.

**Comment by prabirshrestha** [comment]
There is also crossterm now that works on multiple platform including windows and lot of TUI projects in rust seems to now be using this. https://github.com/TimonPost/crossterm

There is a PR for termion that works on windows. https://gitlab.redox-os.org/redox-os/termion/merge_requests/151
