### ISSUE TITLE
Problem with \0 as delimiter

### ISSUE THREAD

**Issue by Aloxaf** [lotabout/skim#253]
Sorry for spamming the issue tracker. I'm developing [fzf-tab](https://github.com/Aloxaf/fzf-tab), which makes heavy use of these special characters.

# Code to reproduce
```
echo $'abc\0def\0ghi' | sk --reverse --height=10 --color='hl+:#ff0000' --delimiter='\0' --nth=2
```

# Result
![图片](https://user-images.githubusercontent.com/17017672/72524978-0bab8600-389e-11ea-9d68-4cd8e0a3b195.png)

# Expected
![图片](https://user-images.githubusercontent.com/17017672/72524949-fcc4d380-389d-11ea-9065-52dc66504749.png)

'\0' seems to need special handling

**Comment by lotabout** [comment]
@Aloxaf `--delimiter` is expecting a regular expression. And I believe `\0` is not a standard one. Use `\x00` or `\u{0000}` instead.

**Comment by Aloxaf** [comment]
It works. Thank you very much!
