### ISSUE TITLE
Can't bind `space:` to an action

### ISSUE THREAD

**Issue by acheronfail** [lotabout/skim#255]
I can't seem to re-bind the `space` key to an action.

What I'm trying to do:

```bash
# Pressing `space` only inserts a space
sk -m --bind 'space:toggle' -c 'ls'
```

I'd expect that pressing `space` would toggle the item, but it just inserts a space into the search box.

Alternatively, using a random character by itself (such as `a`), works:

```bash
# Pressing `a` toggles items
sk -m --bind 'a:toggle' -c 'ls'

**Comment by acheronfail** [comment]
```bash
$ sk --version
0.7.0
```
```
Linux (Arch) 4.19.97-1-lts
```

**Comment by lotabout** [comment]
@acheronfail Confirmed, as a workaround, you could try:

```
sk -m --bind ' :toggle' -c 'ls'
#             `-- note the space here
```
