### ISSUE TITLE
Integration with ripgrep(rg)

### ISSUE THREAD

**Issue by codri** [lotabout/skim#26]
Hi,

I'm trying to use skim with https://github.com/BurntSushi/ripgrep instead of Ag.
I've modified the Ag example command to `sk --ansi -i -c 'rg "{}"'` and the search seems to work.

Though there are a few things that I've noticed, and would be great to have them working.

Line numbers don't show up. Neither when searching nor when then the result is returned.

Let's say we have a folder `test` with two files `a.txt` and `b.txt`. When I start the command above, and type `A`, the following is shown:

```shell
> a.txt:A
  1/1
> A
```

As you can see there are no line numbers shown. The result returned after pressing Enter is `a.txt:A`.

When searching for `A` using the rg command `rg A`, the returned result is:

```shell
a.txt
1:A
```

Also, if line numbers can be returned, I would also like to integrate this with an editor like Vim. It's possible to call vim with the following parameters `vim +{lineNumber} {fileName}`.

Is the integration with ripgrep possible with some configs? Or a code change is required?

**Comment by lotabout** [comment]
@codri For the first part, both `rg` and `ag` will behave differently if piped into some other programs.

```
$ cat a.txt
A
B
C
$ rg 'A' | cat
a.txt:A
$ ag 'A' | cat
a.txt:1:A
```

That means "line number not shown" may be a feature of `rg`, not caused by `skim`.

---

For Integrating `skim` to vim, I have a fork of `fzf.vim`: [skim.vim](https://github.com/lotabout/skim.vim) that integrate `skim` with vim, it provide a command `:AG <pattern>` that enables you to run "skim" inside vim. However it is very immature and suit my own need only.

**Comment by codri** [comment]
Thank you, @lotabout . It looks like rg requires the `--line-number` parameter to work as Ag.

This command has the same behaviour as Ag `sk --ansi -i -c 'rg --line-number "{}"'`. As for vim integration. I was looking for something like `Ctrl-T` in FZF, type vim in the command line then sk and rg would allow me to find the wanted file, with line. Not from inside vim. Not entirely sure how to make this work.

Actually, I wouldn't even need the `Ctrl-T` shortcut, I could map this to v, and skim and rg will allow me to find the file. And it would automatically open in vim(or any other editor).

Which leads me to this question. Can skim change the output format?

**Comment by lotabout** [comment]
@codri `skim` will output the contents just like other traditional Linux filters, that means you may pipe the output to other filters, like:

```
sk --ansi -i -c 'rg --line-number "{}"' | awk -F':' '{print "+"$2, $1}'
```

And perhaps bind it to anything you like. (Actually I not so good at key bindings in shell, so, good luck!)

**Comment by codri** [comment]
Yep. I'm looking at how this is done in FZF: https://github.com/junegunn/fzf/wiki/Examples-(completion)

Maybe will come up with something working.

**Comment by codri** [comment]
One again, thank you @lotabout . Your solution is indeed working, as expected.

```shell
vi $(sk -m --ansi -i -c 'rg --line-number  "{}"'| awk -F':' '{print "+"$2, $1}')
```

It finds the file, and opens it in vim, at the desired line. This is indeed a killer feature, that I'm going to use, over just using FZF.
