### ISSUE TITLE
bind skim to "ctrl+x a" in zsh

### ISSUE THREAD

**Issue by shibumi** [lotabout/skim#261]
Hi,
I try to bind skim to the binding `^xa` in zsh.

My code in looks like this:
```
  function search_all() {
    sk --ansi -i -c 'rg --files --no-ignore --hidden --glob "!.git/*" /'
  }
  zle -N search_all
  bindkey "^xa" search_all
```

When I execute `sk --ansi -i -c 'rg --files --no-ignore --hidden --glob "!.git/*" /'` on command line it works fine. But when I trigger it via the key binding I just get an empty sk output... do you have any idea?

Why am I doing this? - I wanted to have a separate keybinding for searching through my whole filesystem. This helps with some commands that don't provide proper zsh completion for files.

**Comment by lotabout** [comment]
@shibumi Checkout [this](https://unix.stackexchange.com/a/475337) for a workaround to work with zsh:

```sh
function search_all() {
    sk --ansi -i -c 'rg --files --no-ignore --hidden --glob "!.git/*" /' < $TTY
}
zle -N search_all
bindkey "^xa" search_all
```

`sk` will check if the current `stdin` is a tty or not and read the items from pipe if it is not. Zsh however will (possibly) replace the stdin with a pipe in key binding. Which will make `sk` waiting for the pipe thus getting no items at all.

**Comment by shibumi** [comment]
@lotabout I have tested your workaround and sk is inserting a newline at the end. Do you have any idea how i can strip this newline?

**Comment by shibumi** [comment]
@lotabout ok got it.. I just need to add `--print0` :D

**Comment by shibumi** [comment]
@lotabout ok sad, suddenly it stopped working :S I was sure it would work, but seems the whole keybinding is wrong:
```
   function search_all() {
     sk --ansi --print0 -e -m -c "rg --files --no-ignore --hidden --glob '!.git/*' /" <$TTY
   }
   zle -N search_all
   bindkey "^xa" search_all
 fi
```
If I do this: `cp <STRG+x a>` and search for `testfile` I will have the following line in my shell:

`cp /usr/share/testfile`, then I add a ` .` at the end for copying it into the current path. But my zsh interprets this line:
`cp /usr/share/testfile .`
suddenly as: `cp .`

so the actual content that I see in the prompt does not get into the ZSH prompt buffer correctly oO
You can test this via doing `cp <STRG+x a>` and then inserting a path and then trying to go back with your arrow keys.. it will get stucked in the path. No idea how to fix this. :S

**Comment by shibumi** [comment]
Ok, I think i really fixed it now with the following:

```
  function search_all() {
    LBUFFER+=$(sk --ansi -e -m -c "rg --files --no-ignore --hidden --glob '!.git/*' /" < $TTY)
  }
  zle -N search_all
  bindkey "^xa" search_all
```
