### ISSUE TITLE
Indicate when stdin is closed with --inline-info

### ISSUE THREAD

**Issue by Korkman** [lotabout/skim#273]
When piping to skim, the tiny dot indicator in the lower right corner only flashes when lines are received. How to know when a slow search is complete? There should be an indicator for closed stdin.

**Comment by lotabout** [comment]
![image](https://user-images.githubusercontent.com/1527040/75302673-78407a00-5879-11ea-833e-a04418e84c7e.png)

@korkman 
1. When there are still input from either stdin or command output, the spinner would show(50ms after first read)
2. The `dot` in the lower right actually indicates the matcher is working or not.

The spinner is designed for human, the dot is designed for CI. Or please explain your use case if it doesn't meet your need. Thanks!

**Comment by Korkman** [comment]
The spinner seems to be missing with --inline-info.

**Comment by lotabout** [comment]
Trying to add a spinner for inline-mode, just like the following:

```
>  < 5/10
>  - 5/10
>  < 5/11
>  - 5/12
   `--- spinner
```
