### ISSUE TITLE
help with .bashrc function to replace ctrl-r

### ISSUE THREAD

**Issue by derrickcope** [lotabout/skim#274]
Can someone help me with this function to search command history. I know there is a key-bindings.bash script but I don't want all those keybinds. I just want to put it in my .bashrc or .bash-profile. My bash-fu isn't up to the task. The below works but I would like to have it put the selected command in the terminal so I could edit it before I hit return.
Thanks for any help

  ```
skim_history() (
  local line
  shopt -u nocaseglob nocasematch
  line=$(HISTIMEFORMAT= builtin history | sed 's/^ *[0-9]* *//g' | sk --ansi --exact --tac --sync -n2..,.. tiebreak=index --height=30) 
  $line
)
bind '"\C-r": "skim_history\n"'
```

**Comment by lotabout** [comment]
@derrickcope Please refer to this:

```
# CTRL-R - Paste the selected command from history into the command line
bind '"\C-r": " \C-e\C-u\C-y\ey\C-u`__skim_history__`\e\C-e\er\e^"'
```

**Comment by derrickcope** [comment]
Thank you for the reply. I think it is a lot more complicated to paste into the buffer than  I realized
