### ISSUE TITLE
Click on column >= 96 crashes in Screen

### ISSUE THREAD

**Issue by Korkman** [lotabout/skim#277]
Version 0.8.0, when used within Screen (version 4.06.02), crashes when clicking on column 96 and higher. Does not happen in tmux.

```
echo "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000xxxxxx" | sk
```

Click on any x crashes skim with:
```
> thread '<unnamed>' panicked at 'Non UTF8 in input: FromUtf8Error { bytes: [27, 91, 77, 32, 128, 79], error: Utf8Error { valid_up_to: 4, error_len: Some(1) } }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by lotabout** [comment]
Screen will issue mouse event in the x10 style: `^[Mcxy`, `x, y` are the bytes indicating the cursor position. `tuikit` will parse the input into characters and it is no longer valid UTF8 when a byte is >=96.
