### ISSUE TITLE
Can't preview string with nul byte

### ISSUE THREAD

**Issue by Aloxaf** [lotabout/skim#278]
```zsh
> sk --preview-window=down --preview='echo {}' <<<$'abc\0cba'
```

Got an error:

![图片](https://user-images.githubusercontent.com/17017672/75601906-e8a9fe00-5afa-11ea-9fdb-9e6e7e45c9fe.png)

**Comment by lotabout** [comment]
Current fix will translate NUL character to `\0` before invoking the command. However if the command did not understand the meaning of `\0` then it won't work.

**Comment by Aloxaf** [comment]
Another solution is to support `{f}`, which can write the string to a temp file.

eg.
```zsh
fzf --preview='echo "$(<{f})"' <<<$'abc\0abc'
```
