### ISSUE TITLE
Implement '{n}' placeholder expression

### ISSUE THREAD

**Issue by vredesbyyrd** [lotabout/skim#284]
Hi, 

Any plans to implement the `{n}` placeholder? From fzf manpage:

> 
...and {n} is replaced to zero-based ordinal  index of the line. Use {+n} if you want all index numbers when multiple lines are selected.

An example use case, It can aid in grabbing the content of _nth_ line from a file, eg,

`fzf --bind "enter:execute(sed -n \$(({n} + 1))p '/tmp/imdb_url')"`

Thanks for your time.

**Comment by lotabout** [comment]
Closed by https://github.com/lotabout/skim/pull/287, was wrongly numbered in the commit message.
