### ISSUE TITLE
accept_key doesn't seem populated when using as a library

### ISSUE THREAD

**Issue by emmanueltouzery** [lotabout/skim#288]
Hi, skim is super nice! I'm using it as a library. I'd be interested in having several possible actions depending on whether the user presses enter or some other accept shortcut.

This does allow me to register another accept shortcut:

```rust
    let options = SkimOptionsBuilder::default()
        .bind(vec![
            "ctrl-j:accept",
        ])
```

With that option, when pressing ctrl-j the action is acknowledged. However the accept_key I get back is still None:

```rust
    let (selected_items, query, accept_key) = Skim::run_with(&options, Some(rx_item))
        .map(|out| (out.selected_items, out.query, out.accept_key))
        .unwrap_or_else(|| (Vec::new(), "".to_string(), Some("other".to_string())));

    println!("ak {:?}", accept_key);
```

`ak None` is printed even when I use `ctrl-j`. Should I enable some other additional option or something to get notified of which accept key the user used (ctrl-j or enter)?

I also wonder if `skim` takes over the entire screen? Is there some option allowing to put some free-form text on the screen somewhere (for instance instructions, like "Press c-j for X, enter for Y..")?

**Comment by lotabout** [comment]
@emmanueltouzery Try out this option
```
--expect KEYS        comma separated keys that can be used to complete skim
```

**Comment by emmanueltouzery** [comment]
thank you, this works! And I saw in the man page that in that case I should comma-separate multiple shortcuts, that works too:

```rust
        .expect(Some("ctrl-j,ctrl-k".to_string()))
```

and that works great. Maybe I'd just ask again my second question:

> I also wonder if skim takes over the entire screen? Is there some option allowing to put some free-form text on the screen somewhere (for instance instructions, like "Press c-j for X, enter for Y..")?

**Comment by emmanueltouzery** [comment]
hmm I'm thinking that I could maybe use the preview window for that purpose (and maybe as well use it for its intended purpose). I think I could have vertical layout, preview window at the bottom, and put instructions there... Right now I don't see how it wouldn't work, must still try it though.

**Comment by lotabout** [comment]
@emmanueltouzery 
> I also wonder if skim takes over the entire screen? Is there some option allowing to put some free-form text on the screen somewhere (for instance instructions, like "Press c-j for X, enter for Y..")?

Currently no way to achieve this directly.

Alternative option:
1. `--header`: 
    `sk --header='Help: Press c-j for X, enter for Y..'`
![image](https://user-images.githubusercontent.com/1527040/76823611-ae0cc900-684f-11ea-99a4-82c90a7f9e06.png)
2. preview window: 
    `sk --preview='echo "Help: Press c-j for X, enter for Y.."' --preview-window=up:2`

    ![image](https://user-images.githubusercontent.com/1527040/76823661-d72d5980-684f-11ea-994e-f8c5c34f7f81.png)

**Comment by emmanueltouzery** [comment]
thank you very much for all the assistance and answers, and for a great product!
