### ISSUE TITLE
[Feature Request] --reverse

### ISSUE THREAD

**Issue by CallumHoward** [lotabout/skim#30]
fzf has a `--reverse` option that reverses the orientation. This option would be nice in skim

**Comment by lotabout** [comment]
@CallumHoward Thanks for the suggestion.
Would you please give me an use case when this option is helpful?
I myself use the default orientation all the time. Thanks

**Comment by CallumHoward** [comment]
Thanks for a great utility! Here is my use-case:
I have the following function in my .zshrc
```zsh
cf() {
    local dir
    dir=`find . -type d | rg -v "/\.|\.dSYM|\.xcodeproj|build|bin" | sk`
    if [ $? -eq 0 ]; then cd $dir; fi;
}
alias c="cf"
```

where `rg` is [ripgrep](https://github.com/BurntSushi/ripgrep) a faster version of Ag or grep. This allows me to perform very fast fuzzy `cd` straight into a deep directory in a large project. It is commonly one of the first commands I will use in a new shell. On top of this, I am fairly compulsive about clearing the screen with <kbd>CTRL</kbd>+<kbd>l</kbd>.
This results in the prompt being close to the top of the screen. When skim starts, I glance down at the bottom of the screen. If I replace `sk` with `fzf --reverse` the fuzzy search prompt is visually close on the screen to where the shell prompt was.

**Comment by lotabout** [comment]
@CallumHoward You can try the latest release(v0.2.0) for the `--reverse` feature.

**Comment by CallumHoward** [comment]
Perfect! Thank you.
