### ISSUE TITLE
[feature request] sort of initial pre-selection

### ISSUE THREAD

**Issue by paoloschi** [lotabout/skim#309]
I don't know if others might find it interesting; I happen to have scripting situations where such a functionality would be very handy.
A silly example:

```
$ seq 8 14 | sk -m
```
![1](https://user-images.githubusercontent.com/14022008/79844266-bd85b180-83bb-11ea-91df-db72c289c3f6.png)

I figured out a new option that expects a regular expression, something like this:
```
$ seq 8 14 | sk -m --pre-select='^1[0-2]'
```
![2](https://user-images.githubusercontent.com/14022008/79844380-e0b06100-83bb-11ea-817a-7416b9d53b31.png)

If this goes beyond the project aims, please close as of now.

**Comment by lotabout** [comment]
New options are supported:

```
- pre-select-n: select first `n` items
- pre-select-pat: select items that matches regex
- pre-select-items: select items from a preset
- pre-select-file: select items from a preset that's loaded from file
```

**Comment by paoloschi** [comment]
__That's great__!! I 'm very grateful for these new added functionalities!
Endless thanks @lotabout
