### ISSUE TITLE
Benchmark skm vs fzf

### ISSUE THREAD

**Issue by shinokada** [lotabout/skim#317]
If you have any benchmarks data on FZF vs SKIM, please add it to the README.

Thank you.

**Comment by lotabout** [comment]
I haven't done any serious benchmark. But sadly skim is much slower than fzf.

* If the data size is small(e.g. < 100k lines), normally the loading and matching finished "instantly" for both skim and fzf
* When it comes to large datasets, skim is around 2x ~ 3x (or more) slower in my experience.

More details: the bottleneck is more about memory than CPU.
* The overhead of skim's item is 88B while fzf's item is 56B.
* In my experience, skim's memory usage is around 1.5x ~ 2x of fzf's.
* Both skim and fzf's matching algorithm are `O(n)`
* But the size of structure to store matching result is different (skim is bad at it).
* Fuzzy finder is the excellent use case of shared memory, but rust has limited support of it.
* Performance of crossbeam's channel seems to be slower than go(not sure)? It's claimed to be fast, but it's still one of the bottlenecks in skim's use case.

Performance is not something that we take for granted, fzf spent quite a lot of effort in improving it (you could find various tricks in the code). Skim's speed is "acceptable" in nearly all of my daily uses. Thus I don't have the urge to change the situation.

Of course if anyone is interesting at speed up skim, it's very welcome and I'll be ready to help. Thanks!

**Comment by LamaRaz** [comment]
xz -d < 200mb_compressed_list | sk  is almost 2 times slower than fzf and takes almost 2 times the memory

it is sad that something written in a "system's programming language" is that much slower than a garbage collected language.

hopefully something is done. the absurd memory consumption makes it unusable in my case.

**Comment by NightMachinary** [comment]
[**@ghost**](https://github.com/ghost) commented on [Jul 3, 2020, 4:21 AM GMT+4:30](https://github.com/lotabout/skim/issues/317#issuecomment-653264188 "2020-07-02T23:51:54Z - Replied by Github Reply Comments"):
> xz -d < 200mb\_compressed\_list | sk is almost 2 times slower than fzf and takes almost 2 times the memory
> 
> it is sad that something written in a "system's programming language" is that much slower than a garbage collected language.
> 
> hopefully something is done. the absurd memory consumption makes it unusable in my case.
> 
> edit: my use case is enumerating all files on all drives every night and saving to file, then searching through them with fzf.

I have specialized commands for searching different categories (e.g., video and code), and it works well with `fzf`. I also have bound `shift+tab` to search over all the files in the current directory, and it's fast enough to be usable even on the root of my 4TB HDD (though I cache the results in redis to make it even better).

**Comment by timsofteng** [comment]
@lotabout 
Does fzf still faster and more efficient now?

**Comment by sisrfeng** [comment]
I thought programs written in rust  were usually faster than in go...
Being slower, why do we need skim ? 
Also, skim.vim has more bugs than fzf.vim, from my experience.

**Comment by sisrfeng** [comment]
Sorry for the unfriendly comment above.

I have used skim and skim.vim for nearly 1 year, forked them and modified a lot to make them suit me better. But I want to switch to fzf.

Lots of people are improving and extending fzf actively. There are lots of plugins for zsh, vim, etc. (https://github.com/junegunn/fzf/wiki/Related-projects)

Considering the switching cost, I want to know why some users and maintainers prefer skim and whether I should stick with skim.

Maybe fans of skim think rust has more potential than go? 
Look forward to your opinions.

**Comment by sisrfeng** [comment]
Maybe we can stick with skim and wait for new updates.
https://github.com/lotabout/skim/issues/509
https://github.com/lotabout/skim/issues/479

**Comment by mcp292** [comment]
One thing I liked about `skim` over `fzf` was that `skim` includes hidden files by default. You have to manually configure this in `fzf`.

**Comment by LoricAndre** [comment]
This has been added to the README in 926c76ee16072cf19c8b393f67f11513ffae766d
