### ISSUE TITLE
Open in VS code

### ISSUE THREAD

**Issue by shinokada** [lotabout/skim#318]
In stead of this:

```
vim $(find . -name "*.rs" | sk -m)
```

Is there a way I can open it in VS code?

```
code $(find . -name "*.rs" | sk -m)
```

**Comment by lotabout** [comment]
@shinokada Not so familiar with VS Code. The basic idea is that `$(find . -name "*.rs" | sk -m)` would output a list of filenames. Thus if `code` is able to open the listed files then it works.
