### ISSUE TITLE
Any way to adjust how the matcher works?

### ISSUE THREAD

**Issue by xaocon** [lotabout/skim#322]
It would be nice if it was possible to adjust how the matcher works or how "fuzzy" things can be. My main complaint about how things are now is that similar to #320. I often use it to ssh to prior hosts and while it's great about getting matching ssh commands but when I start to type in a host it often don't get good matches if the first couple of letters in the host are common. I'll start to type `ssh ow` and instead of first matching hosts that start with `ow` it will start with other hosts that have ow in them somewhere. I looked a little at tiebreaker but I don't think it would really help because I think it has to do with the fuzzyness.

**Comment by lotabout** [comment]
@xaocon 
1. No able to adjust the detail for matching algorithm for now.
2. You could try `'ssh 'ow` for example for exact match if you know that's what you need.

Hope that helps.

**Comment by ElSamhaa** [comment]
Can we open this? I think it's worth a bit of bump in the roadmap as it can be argued that the current fuzzy-match behavior is not completely correct.
