### ISSUE TITLE
[ Fedora ] Error: Unable to find a match: skim

### ISSUE THREAD

**Issue by kaushalyap** [lotabout/skim#323]
```
❯ sudo dnf install skim
Last metadata expiration check: 4:59:00 ago on Wed 24 Jun 2020 17:13:12 +0530.
No match for argument: skim
Error: Unable to find a match: skim
```

**Comment by lotabout** [comment]
@kaushalyap Thanks for report! However Fedora package is not officially supported. It was initially added by @ignatenkobrain.
@ignatenkobrain could you please help checking if it is still available if you got time?

**Comment by ignatenkobrain** [comment]
Which version of Fedora is it?

**Comment by kaushalyap** [comment]
@ignatenkobrain  It's Fedora 32 with Gnome.

**Comment by ignatenkobrain** [comment]
Thanks, I'll fix this today!

**Comment by ignatenkobrain** [comment]
Should be fixed with https://bodhi.fedoraproject.org/updates/FEDORA-2020-ffe6a4ac9a. Please test it and leave karma there.

**Comment by kaushalyap** [comment]
@ignatenkobrain How long will it take for update to reach the stable channel?

**Comment by ignatenkobrain** [comment]
Should be already there @kaushalyap

**Comment by kaushalyap** [comment]
Yeah it is there! thanks @ignatenkobrain and @lotabout
