### ISSUE TITLE
Question: how to omit the item of the current cursor position when using multi select?

### ISSUE THREAD

**Issue by marcotrosi** [lotabout/skim#330]
Hi lotabout,

I have a question regarding selecting items with -m flag.

sk and fzf both mark items with the TAB key, and both confirm the selection with the ENTER key.

The difference is that when your cursor is on a non-marked item (marked in the sense of having used the TAB key to mark it) then fzf wont add it to the list when I press the ENTER key, but skim will add the item my cursor is on when I press the ENTER key.

This means for me that everytime I iterate a list to decide which elements I want, then in skim I have to put my cursor on an already marked item to confirm my selection, otherwise it will add the element my cursor is on too.
Or I have to know upfront which one will be my last selection, which is my problem.

**How do you handle that? Is there a special confirmation key that does not add the element the cursor is on?**

Why is that a problem?
Imagine the following list that I go through using Ctrl-j/k
•file1
•file2
file3
file4
• file5
file6
file7
file8 - cursor here
file9

lets assume I iterated the list (here a bit short because it's just an example), and I marked the files 1,2,5 and the cursor is on file 8 when I realize that was all I had to select. What now? If I press the Enter key the file8 will be added which I don't want. So with the current implementation I have to go back up to file5 so that I can press Enter to confirm my selection.

This is quite annoying for me, so what is your workflow?

Thank you in advance

marco

**Comment by lotabout** [comment]
@marcotrosi which version of skim do you use? It should be consistent with fzf in the latest version.

**Comment by marcotrosi** [comment]
> @marcotrosi which version of skim do you use? It should be consistent with fzf in the latest version.

0.5.2 via home brew on macOS

**Comment by marcotrosi** [comment]
oh I see there is already 0.8.2 available on GitHub. Maybe I can force home-brew to update. thanks for your reply

**Comment by marcotrosi** [comment]
@lilydjwg just tested for me with a newer version and there it behaves as expected. I now asked at home-brew land for an upgrade.
