### ISSUE TITLE
argument +m from fzf invalid in sk

### ISSUE THREAD

**Issue by Konfekt** [lotabout/skim#335]
In

```sh
# completion.bash (lines 246-247)
_skim_host_completion() {
  _skim_complete '+m' "$@" < <(
```

the argument `+m` is known to `fzf` but not to `sk`, causing an 'invalid argument' error.

**Comment by skbolton** [comment]
I am not a contributor to this project, but I don't think the intent is to have exact feature parity or api alignment with fzf. To enable multi in skim you do `--multi` to disable `--no-multi`.

**Comment by Konfekt** [comment]
This line https://github.com/lotabout/skim/blob/eac57be525e76ff44f82b860a290a517b6fcf85a/shell/completion.bash#L247 is part of  this repo. Does `--multi` achieve what `+m` meant to achieve?

**Comment by skbolton** [comment]
`+m` disables multi select so the correctc option is `--no-multi`

**Comment by Konfekt** [comment]
Thank you!
