### ISSUE TITLE
Preview window size seems to be off-by-one

### ISSUE THREAD

**Issue by zdykstra** [lotabout/skim#339]
Thank you for an excellent piece of software! It's essentially drop-in compatible with `fzf` flags, which is a great achievement! While integrating `skim` into an existing project, https://github.com/zdykstra/zfsbootmenu, I've found that a preview window at the top of the screen is off by -1 row in size. This can be readily tested / compared to the behavior of `fzf` as follows:

`ls | fzf --preview-window="up:2" --preview="echo -e 'test\n{}'"`
This shows two lines: the first with `test` and the second with the file selected from the directory.

`ls | sk --preview-window="up:2" --preview="echo -e 'test\n{}'"`
This shows one line - `test`. In order to show both lines, `up:3` must be used. 

Is this behavior expected, or just an off-by-one error somewhere?

**Comment by lotabout** [comment]
@zdykstra Thanks for loving skim.

The behavior is by design. Skim use only one line instead of a bounding box for preview window.
