### ISSUE TITLE
Add support for multi-line header 

### ISSUE THREAD

**Issue by quentm74** [lotabout/skim#341]
In some of my custom functions in zsh where I use fzf, I use multi-line headers. It would be great if skim supported multi-line headers so I can completely replace fzf by skim.

Here is an example that shows the differences.

```shell
exa | fzf --header $'line1\nline2'
exa | sk --header $'line1\nline2'
```

Thanks for your work !
Let me know if I can help (I looked at the code and I am not sure what would break).

**Comment by quentm74** [comment]
Can you explain me why you closed this issue ?
Aren't you able to reproduce this issue ?

**Comment by lotabout** [comment]
@quentm74 It's supported now on master branch.
