### ISSUE TITLE
Skim as library: provide information about text widths

### ISSUE THREAD

**Issue by wucke13** [lotabout/skim#342]
I'm currently building a CLI tool for configuration management around skim, where skim is used to select a few out of a very huge amount of options. The options have descriptions, with sometimes multi-sentence long explanations. It would be nice to know how to line-wrap these. So in general it would be very nice to know how the width/cols & height/rows of the preview box and the interactive selection part of the screen. Is there an API for that already?

**Comment by MarioJim** [comment]
I'm also building a CLI tool to search pdfs, and would like to access what's currently written in the search box to display the preview. I think a reasonable solution would be passing a reference to the Previewer when calling `SkimItem.preview()` and then accessing the info from there, like [this commit I did](https://github.com/MarioJim/skim/commit/1522d4b32eb922052c06755a0a6099a21ecb9423?branch=1522d4b32eb922052c06755a0a6099a21ecb9423). 
Also, if Previewer is going to be a public struct of the crate, we could make its methods public only inside the crate, [like this](https://github.com/MarioJim/skim/commit/31386e4c6e460dbeb33cd20d226207cb4564d6c0).
