### ISSUE TITLE
Use skim as agrep utility

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [lotabout/skim#343]
Hi!

Is it possible to use `skim` as a some kind of replacement for `agrep` utility? What I want to do: just use command like `history | agrep some_pattern | tail -n 50` without any kind of interaction - only raw results, which can be piped to an another utility.

With `skim` I cannot understand, how to run it without interactive mode.

Thank you.

P.S. I fully understand that under the hood `skim` and `agrep` use different algorithms.

**Comment by lotabout** [comment]
@ZaMaZaN4iK Not sure if this meet your need: `history | sk -f some_pattern | tail -n 50`

**Comment by ZaMaZaN4iK** [comment]
@lotabout oh, you are right. I didn't find this flag in `man` - my bad. Thank you a lot :)
