### ISSUE TITLE
`bat` in the preview command doesn't appear to be rendering colors

### ISSUE THREAD

**Issue by rsyi** [lotabout/skim#348]
First of all, I love this implementation of fuzzy search! I've been building a library that uses fzf, but recently switched to rust and skim and have been overall super happy. Thanks for your hard work!

One problem I've been having, however, is that I'd like to use [bat](https://github.com/sharkdp/bat) for my previews, which provides a really beautiful, colored view of the preview. But the coloring doesn't seem to pass through to the preview window. Running `sk --preview "bat {}"`, for example, produces the following:

![image](https://user-images.githubusercontent.com/28232885/94084838-6dbc7380-fdbb-11ea-81a0-8e5b64db0cc5.png)

while running `bat` from the command-line returns the following:

![image](https://user-images.githubusercontent.com/28232885/94084884-7e6ce980-fdbb-11ea-8e79-dfed3bc90abd.png)

It's something I know works in fzf (see the screenshot below):
![image](https://user-images.githubusercontent.com/28232885/94085197-3ef2cd00-fdbc-11ea-86a3-163f264bdc85.png)

I know this is probably a bit of a niche request, so I'd love to try help on this, but pointing it out here first in case there's an easy solution I'm missing / you had any ideas on this.

**Comment by lotabout** [comment]
@rsyi Would you please try `sk --preview "bat {} --color=always"? I believe it's because `bat` disabled the highlight in "auto" mode.

**Comment by rsyi** [comment]
Beautiful. That works! Thanks! :)
