### ISSUE TITLE
Exa with icons displays wrong colors in preview

### ISSUE THREAD

**Issue by hajdamak** [lotabout/skim#370]
[Exa](https://github.com/ogham/exa) executed with icons option displays colored output like this:
`exa -1 --icons /`
![image](https://user-images.githubusercontent.com/307697/97609181-90bdf100-1a13-11eb-97b8-08c11eb63b92.png)
when executed as preview in skim, for example:
`sk --preview "exa -1 --color always --icons /"`
colors are incorrect :
![image](https://user-images.githubusercontent.com/307697/97609476-f4e0b500-1a13-11eb-897d-15fa36868187.png)

**Comment by lotabout** [comment]
should be fixed by https://github.com/lotabout/skim/commit/3d4be6b294e7161c6e8249e77e4adb2b44246c6e
