### ISSUE TITLE
library: non-interactive mode feature request

### ISSUE THREAD

**Issue by deankarn** [lotabout/skim#373]
First off thanks for this package, exactly what I was looking for fuzzy finding in the terminal.

I was wonder if it's possible now, or in the future, to be able to use the package as a library in a non-interactive mode?

My use case is that I wish to fuzzy find lines from a file using some query input and take the first 5 best matched results. These results will then be forwarded to another piece of software for display and/or selection.

Thanks in advance

**Comment by mporracindie** [comment]
I was going to ask for something really similar so I'm joining this request. 
I know that Skim has a lot of features for dealing with commands and so on but it would be handy if we can use it just as a finder library (without the graphical interface). Do you think this might be possible?

**Comment by lotabout** [comment]
Maybe https://github.com/lotabout/fuzzy-matcher? It is the matching library that skim uses.

**Comment by lotabout** [comment]
Close. Please reopen if more information is needed.
