### ISSUE TITLE
--border not working

### ISSUE THREAD

**Issue by salkin-mada** [lotabout/skim#375]
`sk -v` 0.9.3

`sk --border=sharp --preview='head -$LINES {}'` no borders.
cant get any of these to work: `left|top|rounded|etc|etc..|all of them` :)

same with `export SKIM_DEFAULT_OPTIONS='--layout=reverse --border=rounded'` layout is reversed but no border

maybe some difference from fzf here, something i am missing?

**Comment by lotabout** [comment]
Sorry that it’s not implemented and I am currently not interested in implementing it.

It would be of great help if you could describe when border is helpful.

**Comment by salkin-mada** [comment]
ah i see : -)  . Border is not super helpful. Was just wondering because i am on Arch Linux and i make my own application-launcher, window-switcher, package-manager TUI, etc. using `fzf` and now i ported everything to skim. because `rust` rocks! and skim is so nice.
so back in the pre `sk` days i was using the very limited TUI border thingy on `fzf`. but no need really. maybe i should just use skim as a crate and implement my stuff with the `tui` crate.

thanks for making skim!
