### ISSUE TITLE
Search syntax doesn't work

### ISSUE THREAD

**Issue by xpayn** [lotabout/skim#39]
Hi,

I just discovered skim on reddit and installed it via homebrew on macos sierra.
I've set SKIM_DEFAULT_COMMAND='rg -l ".*"'
when i execute skim on the command line, typing `sk`, using `'`, `^` or other search syntax doesn't work at all (no more matches)
iirc it doesn't work with the default command either.

**Comment by xpayn** [comment]
it seems that the homebrew version is older (0.1.2) than the current.
maybe this syntax wasn't supported at that time
i filled an issue on the formula repo

**Comment by xpayn** [comment]
the formula points now on 0.2.0 which has a working search syntax but is somehow limited:
it seems you cannot combined searches like for instance `^src cpp$ abc` which works in fzf
i guess the space character is matched against like any other character which is not what `fzf` seems to do

**Comment by SirVer** [comment]
Thanks for writing this! I like fzf, but I have trouble getting it to run on ARM, so I am really hoping 
I can add some more examples where skim is not giving the results I expect. I compare `sk -m` vs `fzf -m` in the [Widelands](http://bazaar.launchpad.net/~widelands-dev/widelands/trunk/files) repository.

1) `srcanim` gives similar results (fzf: 34 matches, sk: 35). Annoying is that sk starts every line with `./` - this wastes 2.5% of my terminal real estate.
2) `src anim` gives 1107 matches in fzf and 0 in sk.
3) `'src anim` gives 8 matches in fzf and 0 in sk. 

Especially 2 and 3 are show stoppers for me for switching.

**Comment by lotabout** [comment]
@xpayn Yes, you are right, currently combined search is not supported. But it will in the future.
