### ISSUE TITLE
Toggle between regular expression searching while running

### ISSUE THREAD

**Issue by SirVer** [lotabout/skim#40]
Sometimes I start a search in plain mode and while searching I realize that a regex would be nice. Intuitively I hit `ctrl-r` expecting this to get me into regex search mode, but apparently this gets me into `rotate-mode`.

1) What is `rotate-mode`? It seems not documented.
2) Please consider making a mode to switch to regex search.

**Comment by lotabout** [comment]
@SirVer Thank you for your suggestion.
1. `rotate-mode` is for switching between `interactive mode` and `non-interactive mode`.
2. I will consider about it. One concern is do we need to convert the extended query syntax(e.g. `^prefix` or `postfix$`) into corresponding regex when switching. That would complicate things.

**Comment by SirVer** [comment]
1. this should probably be called `toggle-interactive` then.
2. I would not overthink this - I was not expecting the toggle to keep the current filtering, just the current string. In fact keeping the string is more intuitive than attempting a conversion IMHO.

**Comment by SirVer** [comment]
Toggling to regex mode is a total game changer!! Thanks for this. I switched from fzf to skim now.
