### ISSUE TITLE
FreeBSD: skim does not render properly

### ISSUE THREAD

**Issue by Korkman** [lotabout/skim#412]
Using a fresh install of FreeBSD 13 (minimum install) and skim 0.9.4 via `cargo install skim`, I get this:
![grafik](https://user-images.githubusercontent.com/3186931/118065622-8eaef480-b39d-11eb-94b5-51588efbd5fc.png)

Same rendering issue via SSH and console.

**Comment by jyoung15** [comment]
This issue appears to be related to https://github.com/Stebalien/term/issues/44.  I found that installing `misc/terminfo-db` and exporting `TERMINFO=/usr/local/share/terminfo` resolves the issue for me.

**Comment by lilydjwg** [comment]
Same here on Android termux, with termux' terminal and ssh (from Linux tmux).

**Comment by lilydjwg** [comment]
Well, setting `TERMINFO` to the correct directory resolves this. Obviously it doesn't search the compiled-in default location in ncurses (/data/data/com.termux/files/usr/share/terminfo).
