### ISSUE TITLE
Key Binding for the Terminal

### ISSUE THREAD

**Issue by zkanda** [lotabout/skim#46]
Hi, how do I setup skim with something like this: https://github.com/junegunn/fzf#key-bindings-for-command-line

**Comment by lotabout** [comment]
@zkanda You can check fzf's source code under: https://github.com/junegunn/fzf/tree/master/shell

**Comment by lotabout** [comment]
I've copied the shell scripts from fzf, you can checkout the `shell-binding` branch: https://github.com/lotabout/skim/tree/shell-binding/shell

But I won't include them in the `master` branch, mainly because I have no time to maintain these scripts.
