### ISSUE TITLE
fork this project ?

### ISSUE THREAD

**Issue by github-olivier-abdesselam** [lotabout/skim#479]
Hi,

I've opened a PR ( https://github.com/lotabout/skim/pull/472 ),
tried to contact the main @lotabout both on twitter and via email with no sucess.
I see there's a lot of PRs and issues opened.

Without an answer from main dev, I'm tempted to fork this project, what do you think ?

Would other people be interested in maintaining the fork ?

**Comment by grant0417** [comment]
I use skim as a library in production, have been maintaining my own fork of it just with updated deps, would be willing to help contrib some upstream if we have a new fork.

Only concern is skim is distributed in some package repos so we would either need a new name or to shift those over to the fork.

**Comment by yazgoo** [comment]
Cool,

I guess that without news from @lotabout we won't have a choice to rename.
I think we can give a deadline of next week without news from him to actually go ahead with the fork.

If we suppose a rename is necessary, any suggestion for a new name ?

**Comment by github-olivier-abdesselam** [comment]
Cool,

I guess that without news from @lotabout we won't have a choice to rename.
I think we can give a deadline of next week without news from him to actually go ahead with the fork.

If we suppose a rename is necessary, any suggestion for a new name ?

**Comment by kimono-koans** [comment]
Re: the fork name, some ideas `two_percent`,`whole_fat`?  

Also I want `fzf`'s `--disabled`/select feature for the library!  If anyone can direct me where it might be most appropriate to implement, I'd get to work.

**Comment by TD-Sky** [comment]
Let me try to contact @lotabout in Chinese media and examine his status, OK?

**Comment by yazgoo** [comment]
to help in devs I've created a discord dedicated to this project https://discord.gg/QX2kd6QB

**Comment by TornaxO7** [comment]
> to help in priorizing PRs / devs I've created a discord dedicated to this project https://discord.gg/QX2kd6QB

Could you please update the link? It seems to be invalid.

**Comment by yazgoo** [comment]
Hi, there you gou https://discord.gg/vvwvz7gb

**Comment by qkzk** [comment]
Hello, could you please give a link to the discord ?
I forked skim myself for my own project and would be interested in following along !

**Comment by github-olivier-abdesselam** [comment]
Hi here's a link without expiration:

https://discord.gg/hnNg7AfGHZ

**Comment by yazgoo** [comment]
Hi here's a link without expiration:

https://discord.gg/hnNg7AfGHZ

**Comment by jcsims** [comment]
@yazgoo I'm a big fan of `skim` and prefer it over tools. The discord link isn't working for me, but I'd like to volunteer some time to help maintain, if I can.

**Comment by TD-Sky** [comment]
> @yazgoo I'm a big fan of `skim` and prefer it over other tools. The discord link isn't working for me, but I'd like to volunteer some time to help maintain, if I can.

Here is: https://discord.gg/vzH5Vt5h

@yazgoo should we paste the discord link to README as a shield?

**Comment by github-olivier-abdesselam** [comment]
> > @yazgoo I'm a big fan of `skim` and prefer it over other tools. The discord link isn't working for me, but I'd like to volunteer some time to help maintain, if I can.
> 
> Here is: https://discord.gg/vzH5Vt5h
> 
> @yazgoo should we paste the discord link to README as a shield?

yes, if you want to do the PR I'll merge it

**Comment by TD-Sky** [comment]
I think this issue can be closed now.
