### ISSUE TITLE
Vulnerability in skim because of outdated clap dependency

### ISSUE THREAD

**Issue by mihaigalos** [lotabout/skim#480]
Hi,

Vulnerability  [RUSTSEC-2021-0139](https://rustsec.org/advisories/RUSTSEC-2021-0139.html) has been traced back to skim:

```bash
$ cargo tree
..
skim v0.9.4
├── atty v0.2.14 (*)
├── beef v0.5.2
├── bitflags v1.3.2
├── chrono v0.4.22 (*)
├── clap v2.34.0
│   ├── ansi_term v0.12.1
```

This is because `skim` is not using the latest `clap` version which doesn't have that dependency anymore.
Please upgrade to latest `clap` so that downstream dependents also get the vulnerability fixed.

**Comment by mihaigalos** [comment]
Hi @TD-Sky,
As long as the vulnerability is addressed, whatever works. :slightly_smiling_face:

**Comment by mihaigalos** [comment]
Hi @TD-Sky, any updates here?

**Comment by TD-Sky** [comment]
> Hi @TD-Sky, any updates here?

Sorry, I thought that you had known skim was bumped to clap-3.2.22

My work mainly aims to change the style of parsing arguments in skim (it is using multi-values everywhere for the convenience of accepting default arguments at present).  But I need clap itself to support it. Refer to https://github.com/lotabout/skim/pull/491

Your issue has been solved, but not by me.
