### ISSUE TITLE
Compile on stable

### ISSUE THREAD

**Issue by dead10ck** [lotabout/skim#49]
I've noticed a couple of issues about failing to compile already, but I feel it should be possible to compile on stable Rust. I'm not sure what the `io` feature is (it doesn't seem to be listed in the reference or anywhere my google-fu can reach), so I'm not sure how heavily this project depends upon it, but if there's a way to get around it, it would be great to have binaries built with a *stable* compiler.

**Comment by lotabout** [comment]
@dead10ck `skim` use the `io` feature to [fetch the user input](https://github.com/lotabout/skim/blob/master/src/input.rs#L105). More specifically, use the [io::chars](https://doc.rust-lang.org/std/io/trait.Read.html#method.chars) method.

I understand it is annoying that a nightly version is needed to build skim. I'll try to find an alternative solution.

**Comment by dead10ck** [comment]
Wow, it's very surprising that iterating over characters isn't supported in stable! That seems like a glaring omission. Thank you for your effort to work around it!
