### ISSUE TITLE
[Feature request] Add shell key bindings for fish

### ISSUE THREAD

**Issue by victorz** [lotabout/skim#497]
I am in the process of switching to fish shell and would _love_ to see those good ole shell key bindings to access the history and quickly switch directory like we can in bash and zsh (my previous shell).

Does this need to be done by this project or can I somehow generate key bindings for fish using the existing binds (bash/zsh)?

Thanks for your time and a really awesome piece of software that I use for a _lot_ of stuff, professionally and privately. :smiley:

**Comment by victorz** [comment]
I'll note that fzf has key bindings for fish now:

https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish

**Comment by Delapouite** [comment]
The fish key-bindings bundled with Fzf itself are quite minimal.

For a more complete usage : https://github.com/PatrickF1/fzf.fish

**Comment by victorz** [comment]
Welp, seems like this was added already within the last few releases, so this can be closed!

Simply add this, or similar, to your fish configuration:

```fish
  # setup skim
  if command -q sk
    skim_key_bindings
  end
```

**Comment by znd4** [comment]
@victorz , sorry for a dumb question, but is there some way you're "automagically" getting that function? or did you just "vendor" it into your `$__fish_config/conf.d` dir?

**Comment by victorz** [comment]
> @victorz , sorry for a dumb question, but is there some way you're "automagically" getting that function? or did you just "vendor" it into your `$__fish_config/conf.d` dir?

@znd4, no dumb questions!

Pretty much, yes! That's how it's done. You just run `skim_key_bindings` in your `$XDG_CONFIG_HOME/fish/config.fish` or wherever you wish to put it, so that it runs on every fish instance you start. :slightly_smiling_face:
