### ISSUE TITLE
Separation of skim engine and sk

### ISSUE THREAD

**Issue by YummyOreo** [lotabout/skim#525]
Is it possible to separate skim engine (and all that it depends on) from sk. So you can just import skim engine as a lib?

This would be useful for something like [atuin](https://github.com/ellie/atuin) which only uses the engine.

**Comment by yazgoo** [comment]
Hi, it is already possible to load skim crate and call run_with, e.g.

https://github.com/yazgoo/vmux/blob/6a7c853fb658ffbabaff4bc8aa78eb8e8faa94c7/src/main.rs#L454

**Comment by YummyOreo** [comment]
To clarify atuin uses their own tui not the built in one

**Comment by yazgoo** [comment]
maybe this can be done with features ?

**Comment by YummyOreo** [comment]
Possibly

**Comment by kimono-koans** [comment]
> Is it possible to separate skim engine (and all that it depends on) from sk. So you can just import skim engine as a lib?

You can just use the [fuzzy-matcher](https://github.com/lotabout/fuzzy-matcher) engine.

**Comment by YummyOreo** [comment]
> > Is it possible to separate skim engine (and all that it depends on) from sk. So you can just import skim engine as a lib?
> 
> 
> 
> You can just use the [fuzzy-matcher](https://github.com/lotabout/fuzzy-matcher) engine.
> 
> 

Ill look into that

**Comment by YummyOreo** [comment]
> > Is it possible to separate skim engine (and all that it depends on) from sk. So you can just import skim engine as a lib?
> 
> You can just use the [fuzzy-matcher](https://github.com/lotabout/fuzzy-matcher) engine.

thanks this works!
