### ISSUE TITLE
-c command still running after skim finishes

### ISSUE THREAD

**Issue by cjgu** [lotabout/skim#56]
When running `sk --ansi -c 'rg --color=always --line-number "{}"'` as suggested in the readme, on directories with lots of files (say one's ~/) the inner command still runs (to completion) after sk has exited.

I am using 
```bash
➜  ~ sk --version
0.1.2
➜  ~ rg --version
ripgrep 0.4.0
➜  ~ zsh --version
zsh 5.2 (x86_64-apple-darwin16.0)
```

**Comment by lotabout** [comment]
@cjgu Very sorry for the late reply. Did not have much time to care about it.
Would you please try out the latest version of `sk`: [0.2.1-beta.2](https://github.com/lotabout/skim/releases/tag/v0.2.1-beta.2).
I've tested on my MBP and cannot reproduce your issue.

**Comment by cjgu** [comment]
I can still reproduce it with latest master (cloned repo, cargo build --release, with rust from rustup:
```
stable-x86_64-apple-darwin (default)
rustc 1.16.0 (30cf806ef 2017-03-10)
```

by running:
```
$ /Users/cjg/src/skim/target/release/sk  --ansi -c 'rg --color=always --line-number "{}"'
```
after quitting (not selecting a file), with Ctrl-C, I still have rg running, consuming lots of cpu:

```
$ ps aux | grep ' rg'
cjg              40666 570.6 18.7 14629616 3140892 s013  R     9:35AM   3:08.10 rg --color=always --line-number
```
