### ISSUE TITLE
Proposal: Delete skim.vim repo and recreate it.

### ISSUE THREAD

**Issue by simnalamburt** [lotabout/skim#65]
Hi! I'm an enthusiastic fzf user, and so glad to heard that someone reimplemented fzf in Rust!

I recommend you to delete the [skim.vim](https://github.com/lotabout/skim.vim) repository and recreate it as a plane repository (not as forked repository) for the sake of SEO. Currently, forked repository is not able to be searched in GitHub.

<img width="1188" alt="2017-10-26 10 52 57" src="https://user-images.githubusercontent.com/4435445/32032132-7689437e-ba40-11e7-9d04-e54458dac39f.png">

I happened [for me](https://github.com/simnalamburt/vim-mundo/issues/15#issuecomment-170960926) and [ctrlp.vim](https://github.com/ctrlpvim/ctrlp.vim). As issues, PR, and stars pile up in your repository, this problem becomes increasingly irritating. It's possible to remove the "Forked sign" by contacting the GitHub. But since skim.vim currently has no star, issue, and PR, re-creating the repository is the easiest way to remove that "Forked sign".

Thank you for maintaining Skim!

**Comment by lotabout** [comment]
@simnalamburt Thank you very much for your proposal! I've already recreated [skim.vim](https://github.com/lotabout/skim.vim).
