### ISSUE TITLE
Passing an initial query using '-q' doesn't work as expected in interactive mode

### ISSUE THREAD

**Issue by gilbertw1** [lotabout/skim#66]
When running skim in interactive mode and providing an initial query '-q', the query does not show up in the input prompt and the initial query is not provided to the command, but instead is applied using skims fuzzy matching logic.

For example running:

    sk -i -q 'test' -c 'ls -la | grep "{}"'

will result in 'test' being fuzzy matched against the results of running the command with empty input:

![problem](http://drop.bryan.sh/pQ6Quxf6vL.png)

However, I would expect it to prefill the initial query into the command prompt and have run the initial command with it as input:

![expected](http://drop.bryan.sh/9xqoHGstkY.png)

Thanks!

**Comment by lotabout** [comment]
@gilbertw1 Please use `--cmd-query "<content>"` for specifying query for commands.

**Comment by gilbertw1** [comment]
Works perfectly, thanks for the quick turnaround!
