### ISSUE TITLE
libskim

### ISSUE THREAD

**Issue by emoon** [lotabout/skim#67]
Hi,

Thanks for a great tool! I thought about integrating it in another tool (to match files within a UI) and for me having it as a separate crate would be great! I wonder if you have any plans of separating out the code into a separate crate (which you can also use) but other (Rust) projects can depend on.

**Comment by lotabout** [comment]
@emoon Glad that you like it!

Could you please explain more about your ideas of integration?

As far as I can tell:
1. It is easy to turn the fuzzy searching algorithm into library. Yet crates.io already have many similar crates.
2. Other parts of skim are bound together for now. Skim will need to read in the data asynchronously and cache the data for output, read in user input from terminal and allow user to select multiple items. It is quite impossible for an external product to inject into one of the processes.

Thus it would be better to understand your possible requirements. :)

**Comment by emoon** [comment]
Yeah I guess you are right. I didn't think there were more similar ones around already so it might be better for me to take a look at those and build from that :)

Thanks!
