### ISSUE TITLE
Set CWD as command argument

### ISSUE THREAD

**Issue by nnovikov** [lotabout/skim#68]
Is it possible execute sk with workdir argument?
sk /tmp/ for example.

**Comment by lotabout** [comment]
@nnovikov Not possible.

Depends on what you want to achieve, you could try `cd /tmp && sk`.

**Comment by lotabout** [comment]
If you have any further question, please reopen this issue.

**Comment by nnovikov** [comment]
I don't have question, but I think
`vim $(sk /tmp)`
is better then
`vim /tmp/$(cd /tmp; sk)`

**Comment by lotabout** [comment]
@nnovikov skim is a generalized filter, that makes it strange to be able to set CWD.
- This may make you feel more comfortable: `vim $(find /tmp | sk)`
- Or if you are looking for vim support, please try out [skim.vim](https://github.com/lotabout/skim.vim) as well.

**Comment by nnovikov** [comment]
Generally, you don't need set CWD, I simple use CWD for explanation only.
`vim $(find /tmp | sk)` is longer then `vim $(sk /tmp)` and you dont need use find for current dir, but why sk can't show files not in current dir, but in specific path?
I can write code for it, if you want.
