### ISSUE TITLE
integration for zsh

### ISSUE THREAD

**Issue by allan-simon** [lotabout/skim#69]
it would be great if there was some way easy way to plug skim to the auto-suggestion engine of zsh

**Comment by polyzen** [comment]
[This](https://github.com/lotabout/skim/blob/master/shell/key-bindings.zsh#L60) should be it.

**Comment by lotabout** [comment]
@allan-simon skim had a branch [shell-binding](https://github.com/lotabout/skim/tree/shell-binding/shell) that adapts the scripts of fzf to skim. Please have a try.
I myself know little about bash/zsh scripts, thus won't maintain the scripts.
BTW. PRs are very welcome.

**Comment by lotabout** [comment]
Inactive for long time. Close for now. Re-open if you have further questions.
