### ISSUE TITLE
feature request: allow overriding of arguments in SKIM_DEFAULT_OPTIONS

### ISSUE THREAD

**Issue by magnetophon** [lotabout/skim#70]
When I set
```
export SKIM_DEFAULT_OPTIONS="--preview='~/.local/bin/preview.sh {}'"
```
I can not do
```
sk --preview='ls {}'
```
anymore.

fzf allows this, and it can be very handy.

**Comment by magnetophon** [comment]
Great, thanks!

**Comment by magnetophon** [comment]
I just tested 0.3.2, and I'm still getting:
```
error: The argument '--reverse' was provided more than once, but cannot be used multiple times
```

**Comment by lotabout** [comment]
@magnetophon Currently only the options that takes values will be allowed to accept multiple values.
Em.. I'll think if other options will be necessary.
