### ISSUE TITLE
feature request: execute action for binding

### ISSUE THREAD

**Issue by magnetophon** [lotabout/skim#73]
Another fzf feature: bind a key to a shell command.
See: https://github.com/junegunn/fzf#executing-external-programs

**Comment by aignas** [comment]
Just to show how it would be useful. One can create a nice `git` history browser:
```
# fshow - git commit browser
fshow() {
    git log --graph --color=always \
        --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
    fzf --ansi --no-sort --reverse --tiebreak=index --bind=ctrl-s:toggle-sort \
        --bind "ctrl-m:execute:
    (grep -o '[a-f0-9]\{7\}' | head -1 |
    xargs -I % sh -c 'git show --color=always % | less -R') << 'FZF-EOF'
    {}
    FZF-EOF"
}
```

At the moment skim does not handle this and upon pressing enter it just prints the commit hash and instead I would like to execute the command.

**Comment by sudo-nice** [comment]
Also, that would help to turn skim into a lightweight file manager, being able to delete an entry file, or yank its path, e.g.

**Comment by aignas** [comment]
@lotabout, thanks!
