### ISSUE TITLE
On large lists scroll continues beyond keypress

### ISSUE THREAD

**Issue by bryaan** [lotabout/skim#77]
Replicate:
1. Use `git branch --all  | sk` on a repo with at least 80 branches
2. Hold up or down arrow to scroll, hold for 2 seconds or more, and release
3. Observe the selection continues to scroll for another 2-3 seconds

Interestingly, `rg --files | sk` scrolls fine with more than 500 files.

Anyone else experiencing this?  (using fish shell latest version)

**Update:**
After managing to get the same effect with an rg command I decided it might be related to using powerline/nerdline fonts.  It seems the theory holds weight as changing from Hasklig (Nerdline patched) to Meslo (Nerdline patched) solved the problem.  However, being that they are both nerdline patched fonts there must be more to this story.

Another Update: what I thought was fixed is actually still broken only occurring less frequently.  Haven't determined any further LCD.  Maybe long line is the problem?

**Comment by lotabout** [comment]
@bryaan Since you mentioned that it only happens on `git branch --all`, could you share the repo that this problem occurs? Or find another repo that could replicate the issue with public access.

**Comment by bryaan** [comment]
@lotabout I determined this was not related to `git branch`, instead it would seem the inputs from gitbranch may be causing this, but again only intermittently.  I was able to replicate using other commands including just `rg --files | sk`

**Comment by bryaan** [comment]
I want to say its not skim, the problem is replacing with fzf works just fine.  

I did make progress into replication:  If you open a new window and try to run it, it almost always works fine.  But do some work in the terminal for a while and check again.  At that point it seems only opening a new window will fix it, but notably fixes it in both windows, so make sure to check often.

Is there any possible difference for text output between skim and fzf?
Are you using Terminator?

**Comment by lotabout** [comment]
Thanks for the effort for locating the issue.

I just tried out a git repository that had over 10,000 branches + terminator + Nerd Font Hack, and sadly cannot reproduce the issue...

> Is there any possible difference for text output between skim and fzf?
skim will output more ASCII sequences for drawing.

The reason I can think of is that it takes too much time for skim to draw the output while receiving too much input.

I'll leave the issue here and if anyone else met this issue, please leave some comments here.

**Comment by bryaan** [comment]
> The reason I can think of is that it takes too much time for skim to draw the output while receiving too much input.

Hey that sounds like a very possible cause.  Can't that be fixed?

**Comment by lotabout** [comment]
Close, reopen on any update.
