### ISSUE TITLE
utf8 support

### ISSUE THREAD

**Issue by jbolila** [lotabout/skim#83]
```bash
sk --ansi -i -c 'rg -S -n --color=always "{}"'
```

In the response the utf8 characters aren't showing correctly:

![_empty_filter](https://user-images.githubusercontent.com/728044/40884959-6e5da528-6715-11e8-9317-6f7b84cfcf63.png)

although after the first character everything look fine:

![_empty_filter_one](https://user-images.githubusercontent.com/728044/40884964-899d3bdc-6715-11e8-9ddb-ec6f4e12c16c.png)

**Comment by lotabout** [comment]
@jbolila It is actually `rg`'s problem. `rg` did not output the correct character with empty pattern and color enabled. Please run the command to confirm its output:

```
rg -S -n --color=always "{}"
```

Normally this doesn't bother me so much, but if it means so much to you `ag` would be a good alternative.

**Comment by BurntSushi** [comment]
@lotabout Could you elaborate on your suggestion to use ag here? ag returns an error if you provide it with an empty pattern. So how do you even use ag in the first place here?
