### ISSUE TITLE
fields should behave the same as fzf/cut

### ISSUE THREAD

**Issue by erszk** [lotabout/skim#84]
To recreate this bug:

1. Create a file with some sample input:
`printf "%s\n" /{0..3}/{4..6}/{7..9} > test.txt`
2. See the output of cut, which includes empty fields such as the first one:
```
$ cut -d/ -f3- test.txt | head -n5
4/7
4/8
4/9
5/7
5/8
```
3. Compare the default behavior of `fzf` and `sk` in this regard:
```
unset FZF_DEFAULT_OPTS SKIM_DEFAULT_OPTIONS
fzf -d/ --with-nth=3.. < test.txt
sk -d/ --with-nth=3.. < test.txt
```
When I do this, I see that `fzf` behaves the same as `cut` and `sk` only shows the last fields.

I feel this should be changed to match people's expectations of what a field is and allow for more seamless interaction with other tools like `cut`. This is especially so considering that `sk` and `fzf` are very similar tools and both use the same option names and semantics for "field expressions". At the very least, this difference should be better documented if for some reason this behavior is intended as a feature and not a bug.

**Comment by lotabout** [comment]
@erszk Thanks for the report!

1. Currently skim use git style field expression which excludes last field.
2. It is actually documented here: https://github.com/lotabout/skim#difference-to-fzf

However, I do consider to align the syntax with fzf. I'll consider it as a feature request and keep the issue open.

**Comment by lotabout** [comment]
Done, bump to version 0.5.0
