### ISSUE TITLE
sequence alignment algorithem

### ISSUE THREAD

**Issue by myimages** [lotabout/skim#87]
that is not an issue with Skim but rather a suggestion that worth looking into.

https://github.com/lewang/flx/issues/98

https://github.com/MaskRay/ccls/blob/master/src/fuzzy_match.cc

**Comment by lotabout** [comment]
Sorry for not responding for such a long time. I've finally implemented the algorithm but not satisfied in my own use cases. Thus I won't use it in skim.

If you are interested in the implementation in rust, you could find it in https://github.com/lotabout/fuzzy-matcher/blob/master/src/clangd.rs.
