### ISSUE TITLE
Option to search in the file content?

### ISSUE THREAD

**Issue by dpc** [lotabout/skim#9]
This is an idea/feature request that might be quite a big in scope.

I wish instead of searching just in the file name, the content would be searched (just like in `ag` or `ack`). It is obviously much heavier operation, but for software projects, etc. might be totally feasible.

I wish I could replace `ag` with `skim`, since I like the interactive interface better.

**Comment by lotabout** [comment]
@dpc Nice suggestion!

I think it is a good way to search file contents interactively. However I don't think skim have such features built in, may be we could provide the interactive interface for invoking commands(e.g. `ag` or `ack`) and show the results dynamically.

I mean we should take advantage of current great tools and skim should be an general interface for them. Though, this may not be skim's current target, but I'll think about how to achieve it. Thank you for your suggestion!

**Comment by dpc** [comment]
That would - being able to display results from other commands.

**Comment by lotabout** [comment]
Now we can use `skim` as an interactive interface for invoking commands

Example: `skim -c 'ag --color "{}"' -i --ansi`

It will replace `{}` with the query you type and invoking command `ag` dynamically. `-c` to specify the command, `-i` for `interactive`, `--ansi` for parse ANSI color codes. Of course other commands can be specified.

**Comment by dpc** [comment]
Nice!
