### ISSUE TITLE
How to pass current line as one argument to the preview command?

### ISSUE THREAD

**Issue by lilydjwg** [lotabout/skim#90]
Currently the preview command is invoked by a shell, so when I try to preview a command line (from the history) I can't get it to work correctly because there will be single quotes in the line too. I get syntax errors from the shell when I try to preview complex command line.

**Comment by lotabout** [comment]
@lilydjwg It should be working now in the master branch.

Single quotes are now escaped `'` would become `'\''`. So the following example would work:

```
echo "'" | sk --preview="echo {}"
```

**Comment by lilydjwg** [comment]
It works now, thanks!
