### ISSUE TITLE
sk abortion does not work during indexing

### ISSUE THREAD

**Issue by HongxuChen** [lotabout/skim#92]
When the directory contains large numbers of files/directories (I have totally more than 2015232 files in home directory), during the indexing procedure, it does not respond to key `ESC/Ctrl-G`.
fzf works correctly in this case.

**Comment by lotabout** [comment]
@HongxuChen Did you try the master branch? Maybe related to #89 ?

**Comment by HongxuChen** [comment]
Yes, it's fixed on master. And sorry for not checking past issues carefully.
