### ISSUE TITLE
Get top N matches

### ISSUE THREAD

**Issue by s-panferov** [lotabout/skim#98]
Hello, I would like to implement a search on my documentation website with skim, but I cannot find an ability to just get top N matches in a non-interactive mode. Something like:

```bash
psql database -c 'SELECT * FROM my_table' | sk --query "blabla" --top 100
```

In this case, I want `sk` to return immediately without any user interaction. Is it possible with the current API?

**Comment by lotabout** [comment]
@s-panferov Unfortunately not possible with current API.

It seems to me that what you want is something like `rg` but with fuzzy search support, right?

Skim is designed to be an interactive searcher so I think it is better to build a new tool for what you need (probably with better performance).

**Comment by s-panferov** [comment]
Thanks
